alphagov/ckanext-datagovuk

ckanext/datagovuk/action/get.py
ckanext/datagovuk/auth/__init__.py
ckanext/datagovuk/auth/get.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/test_user_auth.py

During Alpha we wish to be able to authenticate users without needing a
local model, and so here is an API endpoint, callable only by a sysadmin
which will return all of the user's detail on correct submission of
email and password.
The resulting dictionary also contains a list of the organisations that
the user is in.
One stumbling block is that we currently allow emails to be re-used by
different users.  For now we are just using the first such match, but
over time (as per #4) we need to resolve this (if any actually exist).

Add a user_auth endpoint for Alpha.

---

ckanext/datagovuk/templates/organization/snippets/info.html
ckanext/datagovuk/templates/organization/snippets/organization_item.html
ckanext/datagovuk/templates/snippets/organization.html

Removes the logo for publishers, and just puts them one on a line.  Also
removes the same logo from the dataset detail page.
Before:
After:

Template changes for publisher list

---

.travis.yml
bin/travis-build.bash
bin/travis-run.sh

Fixes (and enables) Travis for running the ckanext-datagovuk tests.
Has to update CKAN's psycopg2 dependency for a newer version (not quite sure why this hasn't bitten us with ansible yet) with judicious use of 
```
cd ckan 
.... some stuff  ....
sed -i -e 's/psycopg2==2.4.5/psycopg2==2.7.3.2/g' requirements.txt
```

Fix the travis build script

---

ckanext/datagovuk/templates/home/index.html
ckanext/datagovuk/templates/home/layout.html

Further to card https://trello.com/c/TwLQmz1L/243-remove-search-bar-from-header-s, there was also a search box on the homepage.
Also gives us a template file to customise for further homepage modifications.

Remove homepage search and other homepage clutter

---

ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/test_paths.py
run-tests.sh

Currently all of the publisher routes look like /organization, and this is wrong on at least 2 different levels.  This PR removes all of the routes for /organization* and replaces them with /publisher* so that any requests as follows will resolve properly....
```
url_for('organization_read', id='cabinet-office')
--> /publisher/cabinet-office
```
It also introduces some tests, and a helpful script (./run-tests.sh) which will save having to remember the ultimately forgetful incantation to launch nosetests.
See https://trello.com/c/JzzuMatU/271-overwrite-organization-route-with-publisher-in-ckan

Rename org paths

---

ckanext/datagovuk/helpers.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/templates/package/snippets/resource_form.html

As we need to explore options for allowing file uploads when users are
publishing organogram datasets, we should only show the option when
we can determine it is such a dataset.
Initially, we have no mechanism for starting the process of creating an
organogram dataset, and so we will currently rely on the word 'organogram'
appearing in the dataset title.  This should change once we have a more
accurate way of initiating the process.

Show an upload option if organogram appears in title

---

ckanext/datagovuk/templates/organization/read.html
ckanext/datagovuk/templates/organization/read_base.html

This add the links too view/create harvest sources from publisher pages.  As commented in Trello card, some work will need to be done to get the harvest sources by publisher page displaying correctly.
https://trello.com/c/2AMXSoAx/274-add-harvester-tab-to-organisation-page

Add links to view and add harvest sources by publisher

---

ckanext/datagovuk/lib/cli.py

As the password reset URL is /user/ID?key=KEY the CSV export (after reset)
should contain the ID of the user. Now it does.

When resetting all users' passwords we need the ID

---

ckanext/datagovuk/templates/package/read_base.html
ckanext/datagovuk/templates/package/resource_read.html
ckanext/datagovuk/templates/revision/read_base.html

https://trello.com/c/BuEzsSsc/292-remove-social-media-buttons-from-new-ckan
We don't want users to see the Twitter/Google etc links. It's not possible to override the social media module itself so this PR removes the calls to it instead.

Remove calls to social media links

---

ckanext/datagovuk/templates/organization/snippets/organization_form.html
ckanext/datagovuk/templates/package/snippets/package_basic_fields.html

https://trello.com/b/a30DSRUe/dgu-q1-doing
This PR removes the default domain from the URL preview when creating datasets. We cannot give a full URL path (eg https://data.gov.uk/.....) as those urls contain a data ID that isn't available to CKAN at creation, but Gurinder advises that URL is still an accurate enough label for the field.
It also modifies the preview url for creating a new publisher - since this would be accessed in ckan the default domain is appropriate, but the slug preview name is now "publisher" instead of "organization".
We cannot easily modify the harvester url preview but the default state is appropriate.

Remove domain from URL

---

ckanext/datagovuk/templates/package/snippets/resource_form.html

https://trello.com/c/s8sPyRS3/301-hide-description-field-when-adding-or-editing-a-datafile

Remove the resource description field

---

ckanext/datagovuk/templates/package/read_base.html

https://trello.com/c/4CoDfb8M/366-remove-groups-tab-when-viewing-datasets

Remove groups tab

---

ckanext/datagovuk/plugin.py
ckanext/datagovuk/templates/package/snippets/package_basic_fields.html

This adds a `licence-custom` field so that we can display an optional "Licence Information" field on the dataset form.

Add licence-custom field

---

ckanext/datagovuk/controllers/healthcheck.py
ckanext/datagovuk/plugin.py

For https://trello.com/c/4OwURSFn/329-add-ckan-healthcheck-endpoint
We add this endpoint so that eventually we can monitor uptime metrics. See [documentation](https://docs.publishing.service.gov.uk/manual/uptime-metrics.html#header) for further information about GOV.UK's uptime monitoring service.

Add /healthcheck endpoint

---

.travis.yml
bin/travis-push.sh

In GOV.UK we tag the build with `release_${BUILD_NUMBER}` and also update the `release` branch. We also need to stop Travis building these branches and tags when it notices them.
I decided not to port this to Jenkins yet due to the complexity of the dependencies it requires (CKAN, Solr etc)

Add a script to push release branch and tag on master build

---

ckanext/datagovuk/templates/organization/read_base.html
ckanext/datagovuk/templates/package/read_base.html
ckanext/datagovuk/templates/user/list.html

Removes the public display of publisher usernames (i.e. their email address) by removing the organisation activity feed, dataset activity feed and restricting the 'all users' list to sysadmins only.
https://trello.com/c/cCjocYlo/367-remove-the-public-display-of-publisher-email-addresses

Remove display of publisher usernames

---

.travis.yml
bin/travis-push.sh

Reverts alphagov/ckanext-datagovuk#59
This isn't working so I'm going to revert while we fix it, rather than have "failing" builds.

Revert "Add a script to push release branch and tag on master build"

---

ckanext/datagovuk/templates/package/snippets/package_metadata_fields.html

This field wasn't saving into the database

Fix typo in contact phone field name

---

ckanext/datagovuk/public/datagovuk.css

Before:
After:
https://trello.com/c/w1FlAoGh/375-fix-schema-vocabulary-label-alignment

Fix alignment of 'schema/vocabulary' field and label

---

ckanext/datagovuk/helpers.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/templates/package/snippets/additional_info.html
ckanext/datagovuk/templates/package/snippets/package_metadata_fields.html

For https://trello.com/c/f4LQD6h4/300-update-theme-form-element
* This changes the "Primary Theme" label to "Theme" on the dataset create/edit form as there is no secondary theme (we also update the reference to it on the dataset additional info page):
**Before**
**After**
* In order to make it easier for users to find the right theme, we order the values in the "Theme" dropdown alphabetically: 
**Before**
**After**

Update theme form element

---

ckanext/datagovuk/helpers.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/templates/package/snippets/package_metadata_fields.html

For https://trello.com/c/flpFzetI/377-make-form-lists-show-options-in-alphabetical-order
In order to make it easier for users to find the right option in a form list, we order the values in the "Schema/Vocabulary" and "Code List" form lists alphabetically.
**Schema/Vocabulary - Before**
**Schema/Vocabulary - After**
**Code List - Before**
**Code List - After**

Order form list values alphabetically

---

IMPORT.md
import/incremental_update.py

This script allows us to isolate datasets (and datafiles) that have been modified after a specified timestamp. Therefore we can run an incremental import for only those datasets that have changed after the previous dump.
https://trello.com/c/FNPRIk91/384-delta-sync-between-legacy-and-new-ckan
Original PR: https://github.com/alphagov/datagovuk_ckan_deployment/pull/59

Add script for incremental import of datasets

---

Procfile

In CKAN 2.7, job workers are run using the `jobs` paster
subcommand instead of `celeryd`

Update Celery command lines for newer CKAN

---

ckanext/datagovuk/controllers/user.py
ckanext/datagovuk/lib/authenticator.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/templates/user/request_reset.html
ckanext/datagovuk/templates/user/snippets/login_form.html

This overrides the default CKAN authenticator to lookup the user by email, if their input is not a valid username.
Also allows passwords to be reset by email, instead of username.
Updates the relevant labels from 'Username' to 'Username or Email'.

Allow users to login with their username or email

---

ckanext/datagovuk/public/datagovuk.css

A recently added CSS rule was not specific enough, this targets it at the required areas and removes the knock on effect on other pages.
Before:
After:

Fix box height

---

ckanext/datagovuk/logic/theme_validator.py
import/migrate_datasets.py

Assign a primary theme of 'None' to imported datasets that do not have a theme.
Also allow 'None' as a valid theme in the validator.  This will only ever apply to imported datasets, since the drop-down menu will effectively limit the publisher's choices.

Deal with imported datasets that do not have an assigned theme

---

Jenkinsfile

The "app name" of CKAN is different for deployment than in
this repository, so we specifically have to trigger a build
for `ckan`.

Trigger deploys of CKAN to integration when master builds

---

import/migrate_datasets.py

This ensures we retain the correct data from legacy when importing to new CKAN.
https://trello.com/c/CnrBH5b9/428-make-sync-compatible-with-legacy-geographiccoverage-field

Demote geographic_coverage to extras

---

Procfile

Previously errors were being logged to stderr, which gunicorn
or unicornherder was swallowing.

Log error messages from gunicorn to the error log

---

ckanext/datagovuk/plugin.py

Whilst writing some tests for ckanext-datagovuk, I discovered the `theme-primary` gets validated in the wrong order.  We only want to check if the user has entered a valid theme if there is actually some content to check.

Correct the order of validation for theme-primary

---

README.rst
bin/jenkins-tests.sh
bin/travis-run.sh
ckanext/datagovuk/helpers.py
ckanext/datagovuk/templates/package/snippets/resource_form.html
ckanext/datagovuk/tests/test_helpers.py
run-tests.sh

This PR enables the upload feature for only organograms (identified by having a schema vocabulary of either `d3c0b23f-6979-45e4-88ed-d2ab59b005d0` for government departments and `538b857a-64ba-490e-8440-0e32094a28a7` for local authorities).
Additionally, it fixes an issue where tests that interact with the database do not work on Jenkins, by ensuring the database is properly initialised before commencing any tests.
Trello card: https://trello.com/c/odHiWSoq/63-implement-upload-organogram-to-s3

Allow uploads for organograms only

---

bin/install-dependencies.sh
requirements.txt

Adds in the `ckanext-s3-resources` plugin that replaces the default CKAN upload behaviour to local storage with uploading to S3.  This change enables to installation to be done by Jenkins.
Trello card: https://trello.com/c/odHiWSoq/63-implement-upload-organogram-to-s3

Install the S3 plugin during build

---

Procfile

CKAN uses Pylons so is already a WSGI app.  There is no need for us to create a WSGI wrapper to run CKAN in.

Simplify the gunicorn set up for CKAN

---

ckanext/datagovuk/plugin.py
ckanext/datagovuk/templates/header.html
ckanext/datagovuk/tests/test_paths.py

Trello card: https://trello.com/c/JJfnLj1g/57-remove-google-analytics-plugin

Remove link to Site Analytics page

---

bin/install-dependencies.sh

We have been installing CKAN 2.7.0, but have been developing with CKAN 2.7.4.  This installs the correct version.

Bring CKAN up to the same version as in the dev VM

---

ckanext/datagovuk/logic/theme_validator.py
ckanext/datagovuk/public/datagovuk.css
ckanext/datagovuk/templates/package/snippets/package_metadata_fields.html

The following fields were poorly formatted and resulted in confusion during user testing:
- Theme
- Schema Vocabulary
- Codelist
This adds a blank default option (rather than selecting the first alphabetically) and only permits one option to be selected.
Before:
After:
Trello card: https://trello.com/c/9f0G6D2C/77-make-the-schema-vocabulary-and-code-list-selection-boxes-nicer-to-use

Tidy the dropdown menus on dataset creation form

---

ckanext/datagovuk/controllers/user.py
ckanext/datagovuk/lib/authenticator.py

Currently, if a user attempts to log in and their entry matches neither a username or email address, they get served a 500 error.
This deals with that by ensuring that this instance is captured and an error message served to the user.
Trello card: https://trello.com/c/dLWqvdLB/78-fix-500-error-logging-in-when-email-does-not-have-an-account

Gracefully exit if a non-existent username/email is entered

---

ckanext/datagovuk/logic/validators.py
ckanext/datagovuk/tests/test_user.py

Increase password strength by requiring passwords to contain and at least one upper and one lower case character.
Trello card: https://trello.com/c/zCTzerSB/53-require-a-capital-letter-in-password

Enforce passwords requiring both upper and lower case characters

---

ckanext/datagovuk/templates/source/admin_base.html
ckanext/datagovuk/tests/test_harvest_admin.py
setup.py
test-jenkins.ini
test.ini

This doesn't behave the way users will expect given other changes
to our CKAN, so we're just going to remove it.
This is the minimal amount of template I could copy over from the
harvest plugin, unfortunately there's no more granular `block` hooks to
override.
This means we should keep an eye on changes to this section of the
template when upgrading the harvest plugin.
https://trello.com/c/aAiZQ3sK/90-remove-the-clear-button-from-harvest-source-page

Remove the "Clear" button for harvest sources

---

ckanext/datagovuk/templates/package/resource_read.html
ckanext/datagovuk/templates/package/snippets/resource_item.html

Resource names were being truncated at 50 characters on both the list of resources and also the actual resource itself.  This meant that a publisher could not differentiate between resources that have the same first 50 characters.
This PR removes truncation in both places and removes the green 'More' button, which confused users during testing and simply duplicates the behaviour of clicking the resource name.
Before:
After:
Trello card: https://trello.com/c/PU1T4N10/54-data-file-names-are-truncated

Remove truncation of resource names

---

Jenkinsfile
bin/install-dependencies.sh
requirements.txt

This makes it easier to keep versions of eggs and their requirements in sync.
We shouldn't *need* to do this, but it seems the developers of these eggs haven't properly specified their own dependencies.
https://trello.com/c/pxc8vszb/89-get-ckan-running-in-staging-and-production

Install deps in the same file

---

bin/jenkins-tests.sh
test-jenkins.ini
test.ini
who.ini

There were two test configurations: `test.ini` and `test-jenkins.ini`.  These both inherited another configuration from core CKAN, which is located in a different location for each test environment.
Changes to the test configuration had to be made in both files, which resulted in duplication of effort and possibility for things to be missed.
This change removes the inheritance from core CKAN and removes duplication from `test-jenkins.ini`, which now inherits as much as possible from the main DGU test configuration.
Trello card: https://trello.com/c/IAIVU3Vc/92-just-use-one-ini-file-in-local-and-jenkins-testing

Remove inheritance from CKAN for testing

---

ckanext/datagovuk/plugin.py
ckanext/datagovuk/templates/base.html

It is currently not included in the same way as other resources (using Fanstatic).  This fixes that.

Correctly include the DGU CSS as a resource

---

ckanext/datagovuk/i18n/en_GB/LC_MESSAGES/ckan.po
ckanext/datagovuk/public/datagovuk.css
ckanext/datagovuk/templates/home/layout.html

Removes the default CKAN homepage content and design.  Replaces with content similar to that planned for the new Publish app.
Before:
After:
Trello card: https://trello.com/c/ZhPoqwZp/123-update-ckan-homepage

Update CKAN homepage layout and content

---

ckanext/datagovuk/templates/source/read_base.html

This creates a link to `/harvest/admin/` rather than `/harvest/admin/source-name` at the moment.

Fix typo that stops Manage Harvest button working

---

migrations/001_bytemark_to_govuk.sql

The organogram viewer has been implemented in Find, so it is no longer necessary to have a link to CKAN as one of the resources.
Trello card: https://trello.com/c/VC7gQm5p/128-remove-links-to-organogram-viewer

Soft-delete the organogram viewer resources during migration

---

migrations/001_bytemark_to_govuk.sql

There were two issues with the SQL migration process:
- We were deleting sysadmin users, when they should have just been demoted
- There is a not null constraint on the `name` column so we should only update where there is a non-null value
Trello card: https://trello.com/c/IOJpy2to/126-document-process-for-getting-postgres-database-dump-onto-aws

Update SQL migration script

---

ckanext/datagovuk/helpers.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/templates/base.html
requirements.txt

The tracking ID is configured separately in `ckan.ini` (https://github.com/alphagov/govuk-puppet/pull/8484).
Trello card: https://trello.com/c/zBKmvCwm/137-add-google-analytics-to-ckan

Add Google Analytics tracking code

---

ckanext/datagovuk/forms/publisher.py
ckanext/datagovuk/helpers.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/templates/organization/snippets/organization_form.html

Adds a new extra to the publisher schema named 'category'.  Find uses this field to boost datasets from certain categories of publisher in the search results.
Trello card: https://trello.com/c/ltVoVvQu/139-add-a-category-extra-to-the-publisher-schema

Add a 'category' extra to the publisher schema

---

migrations/001_bytemark_to_govuk.sql

The updated harvest plugin appears to validate the data each time `setup` is run.  Fixing these issues as part of the upgrade database migration will remove this error from being logged.
There are two changes being made:
1. DKAN harvesters are not being supported in new CKAN.  There is only one publisher using this format, so their source is updated to `data.json` so they can continue to harvest.
2. One local authority's harvest source has been entered twice with a different slug but the same source URL.  There is additional URL validation on the harvest sources in newer versions of the harvest plugin which prevents duplication of URLs across harvest sources.
Trello card: https://trello.com/c/GLb5wFtg/140-fix-harvest-source-validation-errors

Fix harvest source validation issues

---

ckanext/datagovuk/forms/publisher.py

When this is mandatory in the DB to form schema it causes a 500 when
dumping the object to JSON if the extra is missing.
Because we have some categories missing in the DB, this change
allows us to render the orgs with the missing category but
requires a category to be provided if saving the org.

Make category an optional extra when showing orgs

---

Procfile

This allows us to ensure that gunicorn has the same timeout
as nginx.
https://trello.com/c/2rnVLIgT/726-fix-timeout-on-organogram-publishing-recommended-%F0%9F%8D%90-for-dgu-learning
Relies on https://github.com/alphagov/govuk-puppet/pull/8614

Set a gunicorn request timeout from puppet

---

ckanext/datagovuk/helpers.py
ckanext/datagovuk/tests/test_helpers.py

This is so that publishers can validate their datasets against it.
Schemas are used to validate datasets on data.gov.uk against a
specification.
The geospatial commission is doing some work at the moment that they
want to make sure complies to a schema that hasn't been used on
data.gov.uk before.
Trello: https://trello.com/c/KkaFHYpE/749-add-a-new-schema-to-datagovuk

Add GC-Data-Catalogue-csv-schema

---

ckanext/datagovuk/templates/robots.txt

The way we use CKAN is purely as an administration interface to manage the datasets which are rendered on data.gov.uk using a separate 'Find' application.
Therefore we don't want any robots to be indexing any of the pages in CKAN as they will only be accessible to people who have logged in.
Also we hope this will reduce the 5xx rate on CKAN as bots are frequently requesting a page which is raising a 5xx error and we'd rather stop them accessing this page rather than fixing the issue in CKAN itself.
This is based off [the official template from CKAN](https://github.com/ckan/ckan/blob/master/ckan/templates/robots.txt) but with modifications. As I understand it, templates in plugins will overwrite built in templates.
[Trello Card](https://trello.com/c/PonNGWyO/797-stop-search-engines-from-ind …

Disallow indexing by search engine bots

---

Procfile

Previously CKAN used to use celery to process background jobs, but since
the migration we were actually using CKAN's new in-built workers, so we
should at least rename them in the Procfile. However, it turns out these
workers haven't been running in prod for 120 days(!), which indicates
they're not necessary and listing the queues shows they're empty.
https://docs.ckan.org/en/2.8/maintaining/background-tasks.html#migrating-from-ckan-s-previous-background-job-system

Remove redundant 'celery' workers

---

bin/install-dependencies.sh

https://github.com/alphagov/ckanext-spatial/pull/8
https://github.com/alphagov/ckanext-harvest/pull/4
These extensions have been updated, and in the case of harvest, diverged again
from the main branch. This PR updates the hashes in the dependencies script
to point towards the master branches of our own forks for both extensions.

Update ckanext-spatial and ckanext-harvest

---

ckanext/datagovuk/action/create.py

When a user uploads a file which appears to be an Excel file, we check the schema vocabulary to see if the file should be processed as an organogram.
This fixes an issue where a 500 error is produced when users upload XLS files without selecting a schema-vocabulary.
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/3666591

Fix error when uploading XLS that has no schema vocabulary

---

ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/test_paths.py

Without this redirection the ckan stack respond with a 500 error when a user attempts to go to `/home`.

Redirect /home requests to /

---

migrations/002_fix_organograms.sql

These come from pre-migration and seem to be in a format that CKAN doesn't understand, so we can remove the `["` and `"]` parts to fix them.
```
ckan_production=> SELECT COUNT(*) FROM package_extra WHERE value = '["538b857a-64ba-490e-8440-0e32094a28a7"]';
count
-------
18
(1 row)
ckan_production=> SELECT COUNT(*) FROM package_extra WHERE value = '["d3c0b23f-6979-45e4-88ed-d2ab59b005d0"]';
count
-------
250
(1 row)
```
[Trello Card](https://trello.com/c/SpUg2rd1/971-fix-tagging-for-dgu-organograms)

Fix incorrect organograms schema/vocabs values

---

bin/install-dependencies.sh

Spatial sha contains fixes for Gemini WAF harvesters to show better errors to users so that they can work on fixing their WAF page.

Update to use spatial sha 7bdc8c5

---

bin/install-dependencies.sh

This includes the latest changes made in https://github.com/alphagov/ckanext-s3-resources
Commit: https://github.com/alphagov/ckanext-s3-resources/commit/8014055db7830e4cdd49a7184ef3a1d56613a3a3
Trello card: https://trello.com/c/5KrmZ1tb/1025-fix-bug-to-show-visualisation-on-junior-post-organograms

Update sha commit for ckan_s3_resources

---

ckanext/datagovuk/action/create.py
ckanext/datagovuk/tests/action/test_create.py

Currently, even if the uploaded `xls` file has more than one validation issue, only one error message is displayed, making the process painful for the user. This PR fixes this problem, allowing the user to see all error messages at once.
It also makes the system accept `xlsx` files, instead of only `xls` files.
Trello card: https://trello.com/c/i57HcWI7/983-check-that-organogram-validation-is-working-as-expected

Show multiple validation errors

---

bin/python_scripts/fix_organograms_s3_filenames.py

- also fixes the script when deployed on to prod to run paster solr reindex

Remove break when it detects more than 1 pair

---

bin/python_scripts/fix_organograms_s3_filenames.py
bin/python_scripts/tests/test_fix_organograms_s3_filenames.py

- In order to pair remaining filenames the script checks if the junior timestamp was within 30 seconds of the senior.
- also report on any unpaired files

Update filename script to handle multiple filenames

---

README.rst
ckanext/datagovuk/plugin.py
requirements.txt

Rather than using a custom CKAN plugin I've decided that the simplest way to enable Sentry error reporting is to implement it ourselves in this plugin.
All the CKAN Sentry plugins I looked at were a few years out of date and didn't support the new [Sentry SDK](https://github.com/getsentry/sentry-python).
Although this means that we now have to maintain this code, it's fairly simple and most of the work is done by the Python module itself.
Depends on https://github.com/alphagov/govuk-puppet/pull/9311.
[Trello Card](https://trello.com/c/Xv7JmC8g/1084-add-sentry-to-ckan-stack)

Add error reporting to Sentry

---

bin/python_scripts/remove_march2019_duplicates.py

There were a number of duplicate datasets arising from the upgrade of the ckan stack earlier this year. 
When the harvesters were fixed there were other issues which eventually got fixed at the end of March but the duplicate datasets had already been created in error.
In order to cleanly remove datasets from the ckan stack it is best to use the ckan cli `dataset delete` option which also updates the `solr` index.
For belts and braces approach we also store the affected datasets in a deleted_datasets.csv file in case we need to undelete a dataset as it is possible that valid duplicate datasets were created in March.
In order to rollback we need to identify the datasets and set the package state to active via the database, then we run a solr reindex - more details here - …

Add python script to remove duplicate datasets

---

bin/install-dependencies.sh

This update will deploy a fix for spatial harvesters which will allow users to import datasets that share the same name across ckan, it was being limited to 100, but this limit has now been lifted.
https://trello.com/c/7prmDou5/1082-that-url-is-already-in-use-error-message-when-reharvesting

Update spatial sha to install spatial harvest fix

---

bin/install-dependencies.sh

Update the shas to enable users to force import targeted guids when using harvest `run_test` and also update Spatial to use the right version of WMS in OWSLib.
After this has been deployed we will be able to actually do the work - https://trello.com/c/EbxLlTzk/117-run-the-tasks-to-fix-wms-map-previews
WMS previews were not being shown on data.gov.uk because the format was not identified so the preview link did not appear. 
https://trello.com/c/bomJEEnz/1112-investigate-wms-map-preview-not-being-available-for-some-records

Use harvest 0ba5e and spatial 0e528 sha

---

bin/install-dependencies.sh

This should fix the deployment of ckanext-spatial on new stacks

Update spatial sha to fdae1

---

bin/install-dependencies.sh
requirements.txt

It was decided that we add pycsw here to support the `csw` endpoint as it makes the pulling in of ckan dependencies consistent.
We might have been able to add it as part of spatial but as we are planning on merging our fork back and not all spatial users need the `csw` endpoint served it is better to keep it out.
The `pycsw` version is quite old at `1.8.3`, this is the current working one. Later versions were attempted but there are some odd behaviours which will take some time to investigate. For now it is good enough.
This needs to be merged in before the update to `govuk-puppet` for `csw` can be run.
https://trello.com/c/RudwUlvN/1157-update-govuk-puppet-to-deploy-ckan-with-pycsw

Add pycsw setup as part of datagovuk ckan build

---

bin/install-dependencies.sh

Needed to set the `env` before running python to get the correct pip install location.

Set env before python on dep script

---

setup.py

- Fix 'error: no such option: --with-pylons'
(From Pylons 1.0.1, the nose plugin is not registered by Pylons itself
any more.)

Fix Jenkins

---

Procfile
ckanext/datagovuk/pycsw_wsgi.py

To run the PyCSW server, we need to have it configured in the Procfile so that we can generate an Upstart service for it.
This runs the `pycsw.wsgi` file (provided by the `pycsw` module) using gunicorn.
[Trello Card](https://trello.com/c/RudwUlvN/1157-update-govuk-puppet-to-deploy-ckan-with-pycsw)

Add PyCSW to the Procfile

---

ckanext/datagovuk/action/get.py
ckanext/datagovuk/pii_helpers.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/action/test_get.py
ckanext/datagovuk/tests/test_pii_helpers.py

Removes PII determined by keys defined in PII_LIST in `ckanext/datagovuk/pii_helpers.py`
`package_search` and `package_show` were overridden by copying the code over to this repo. This is in line with how this repo overrides core ckan functions and how other extensions are doing this.
https://trello.com/c/GrO3ZtIR/1228-remove-personal-data-from-ckan-api-endpoints

Remove PII from package search & show

---

ckanext/datagovuk/action/get.py
ckanext/datagovuk/controllers/api.py
ckanext/datagovuk/pii_helpers.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/test_pii_helpers.py

The CSW sync task uses the `api/search/dataset` endpoint to get information from ckan, so after PII information has been removed and this has deployed and puppet updated with the endpoint safelisted the CSW endpoint and sync needs to be checked.
https://trello.com/c/RudwUlvN/1157-update-govuk-puppet-to-deploy-ckan-with-pycsw

Remove PII from api/search/dataset endpoint

---

ckanext/datagovuk/action/get.py
ckanext/datagovuk/plugin.py

Remove the users block from `organization_show` endpoint to prevent exposure of hashed emails and user names.
I've carried out an end to end test locally up to the Find app and it appears to be working.
https://trello.com/c/ukgvMRf4/1246-remove-users-block-from-ckan-api-organizationshow-endpoint

Remove users block from organization_show

---

ckanext/datagovuk/pii_helpers.py
ckanext/datagovuk/tests/test_pii_helpers.py

The api request by pycsw requests specific fields, we should not introduce additional fields if they are not provided.

Only update fields that are present in the data

---

ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/test_plugin.py
setup.py

Users were unable to update harvested datasets and got this error on the ckan publisher - 
```
The form contains invalid entries:
junk: The input field [('harvest', 0, 'value'), ('harvest', 0, 'key'), ('harvest', 1, 'value'), ('harvest', 2, 'value'), ('harvest', 1, 'key'), ('harvest', 2, 'key')] was not expected.
```
This was eventually traced to `augment_data` function which would check if any additional fields were added to the package dict. 
I was expecting `schema['harvest'] = [ignore]` to inform ckan to ignore that field but that didn't work, a work around was found that does work - `schema['harvest'] = {'_': ignore}`
An issue was created in ckan to see if there is a better way of doing this - https://github.com/ckan/ckan/issues/4989 or for the ckan team to improve their docs or fix …

Update package_schema to ignore harvest element

---

bin/install-dependencies.sh

Add errors from WMS check in `ckanext-spatial` to be reported back to users on ckan publisher.
https://trello.com/c/QzELjbIB/1310-5-investigate-why-the-format-for-some-spatial-datasets-are-not-populated-and-fix-it

Update dependencies to spatial commit 8c4189

---

bin/install-dependencies.sh

The latest spatial commit gets the WMS version from the root and also fixes tests which were broken when `force-import` was introduced.

Update dependency to latest spatial commit

---

bin/install-dependencies.sh

This spatial commit should upgrade pycsw to 2.4.0 and use the spatial commit 43f27a which has updated code to use pycsw 2.4.0 and ensure that OWSLib 0.18.0 is available in the virtual env.
I have also carried out additional checks on Integration to ensure that CSW load still works.

Update dependencies to use latest spatial commit

---

ckanext/datagovuk/templates/package/snippets/package_metadata_fields.html
ckanext/datagovuk/templates/source/new_source_form.html

There's a feeling that publishers might not be aware of where the data they enter will be displayed. The GDS Privacy Team want us to add these warnings - that will make them more comfortable showing data from these fields.
[Trello Card](https://trello.com/c/dD6rWy3M/1431-5-add-more-warnings-for-publishers-about-personal-data-%F0%9F%8D%90)

Add warnings about personal information

---

ckanext/datagovuk/pii_helpers.py

These contact details are not PII and may be shown.
[Trello](https://trello.com/c/h7vAgmX9/1430-3-show-contact-details-for-datasets%F0%9F%8D%90)

Remove contact details from PII exclusion list

---

bin/install-dependencies.sh

Update the `ckanext-spatial` sha to enable better logging when duplicate GUIDs are in the same harvest source, and prevent datasets from being silently overwritten.

Update spatial sha to 24fcbc

---

bin/install-dependencies.sh

The spatial update fixes a bug to handle datasets that do not have the source url information as part of a check on duplicate guids within a harvest source.

Update dependencies to use spatial b86a7

---

bin/install-dependencies.sh

This harvest commit pulls in commits upstream so that the alphagov fork is aligned with ckan upstream.

Update dependencies to use latest harvest commit

---

bin/install-dependencies.sh

We can deploy with the updated sha which is linked to the commit in spatial without it being merged into spatial master as there may be other changes we will need to make on spatial to get it merged upstream.

Use spatial sha with upstream commits

---

migrations/003_update_environment_agency_contact_email.sql

Environment Agency has requested that the contact email for harvest sources that have retired be updated as they are unable to update them. 
https://trello.com/c/LVndkOcl/1665-bulk-update-environment-agency-enquiries-email-across-datagovuk

Updates the environment agency email

---

bin/python_scripts/solr_reindex_target_date.py

As Publish and CSW use the CKAN API which in turn uses SOLR to extract data, we need to ensure that SOLR is reindexed if we make ad hoc changes to the database. 
As long as the `metdata_modified` date is later than the one set in the Publish DB, the dataset will be updated.
https://trello.com/c/LVndkOcl/1665-bulk-update-environment-agency-enquiries-email-across-datagovuk

Add solr reindex script that targets a date

---

ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/test_paths.py
requirements.txt

This was removed 2 years ago from core CKAN but is required for us
to route to organisations correctly. See ckan/ckan@e397e4c#diff-d48c332d8b78785e88afaf8406c9fff3
This patch also means we can defer the work on upgrading the pages
to flask views.
Trello card: https://trello.com/c/dljuAYRk/1691-5-fix-publisher-form-in-datagovuk-extension-in-docker-ckan-28-%F0%9F%8D%90

Patch guess_group_type for /publisher routes

---

ckanext/datagovuk/action/create.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/action/test_create.py
ckanext/datagovuk/tests/test_s3_resources_plugin.py
ckanext/datagovuk/tests/test_upload.py

The timestamps in the filenames were different for senior and junior csv files which meant that the frontend was not able to find the files. 
This fixes the timestamp to be the same for junior and senior csv files.
https://trello.com/c/Q7t5BErs/1742-fix-timestamp-when-uploading-organogram-in-ckanext-datagovuk

Fix upload timestamp

---

ckanext/datagovuk/action/create.py
ckanext/datagovuk/tests/action/test_create.py
ckanext/datagovuk/tests/test_upload.py
ckanext/datagovuk/upload.py

The s3 url contained a filename with an additional extension which meant that the javascript code to visualise an organogram failed to work.
Also the upload resource was moved so that the settings following an upload would be correctly set.
Fixes organogram visualisation
https://trello.com/c/Q7t5BErs/1742-fix-timestamp-when-uploading-organogram-in-ckanext-datagovuk

Fix s3 filename

---

ckanext/datagovuk/tests/test_package.py
ckanext/datagovuk/tests/test_paths.py
migrations-2.8.md
test.ini

These tests should help us with the upgrade to 2.8
Trello card: https://trello.com/c/GJ7FxlvE/1718-8-add-datagovuk-tests-to-capture-the-failing-parts-of-the-upgrade-to-ckan-28-%F0%9F%8D%90

Add additional tests for 2.8

---

bin/python_scripts/fix_organograms_s3_filenames_exts.py

This script reuses some code from fix_organograms_s3_filenames.py
It renames the s3 files and updates the urls with the correct path.
Fixing the path enables organogram visualisations to work.
https://trello.com/c/Q7t5BErs/1742-fix-timestamp-when-uploading-organogram-in-ckanext-datagovuk

Add script to replace .csv.csv with .csv

---

ckanext/datagovuk/action/update.py
ckanext/datagovuk/ckan_patches/__init__.py
ckanext/datagovuk/ckan_patches/cli.py
ckanext/datagovuk/lib/mailer.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/action/test_update.py
ckanext/datagovuk/tests/test_ckan_patches.py

Send an email to the user whenever their password changes, either from the GUI, from a reset link or from the CLI.
There was an incident when the password was reset but no one knew how, this should add additional logs for when password get changed so that we have more visibility if someone attempts to gain unauthorised access.
https://trello.com/c/EQcYxINw/1755-5-implement-email-alerts-to-users-when-their-password-is-changed-in-ckan

Add password change email

---

bin/install-dependencies.sh

Our changes have been merged upstream now so we can update our 
dependencies to point to CKAN's core extensions.
Trello card: https://trello.com/c/2TNyfgsJ/1765-5-update-datagovuk-to-use-ckan-core-extensions-and-archive-redundant-forks

Update dependencies to use CKAN core extensions

---

bin/install-dependencies.sh
dev-requirements.txt
requirements.txt

In order to use the harvest commits introduced by DGU, we have to pin the dependencies to a commit rather than a release version in ckan/ckanext-harvest.

Use upstream DGU harvest commits

---

requirements.txt

CKAN 2.7.4 installs six 1.10.0, but ckanext-harvest needs six 1.12.0, so pin six to 1.12.0 to fix ckanext-harvest dependency issue.

Pin six to 1.12.0 for ckanext-harvest

---

bin/install-dependencies.sh

The DGU upstream merged commit caused a problem with Staging which didn't appear in Integration or on local stacks. There is a fix, https://github.com/ckan/ckanext-harvest/pull/395,  waiting to be merged in which once merged in we will try to use the latest upstream commit.

Revert back to latest ckan harvest release

---

ckanext/datagovuk/pii_helpers.py
ckanext/datagovuk/tests/test_pii_helpers.py

Sometimes the response is a list of strings and not json elements, so we should avoid trying to remove PII from the string otherwise we get a 500 server error.

Only remove PII for json element with keys

---

bin/install-dependencies.sh

The problem that meant we couldn't switch to this version has been fixed: https://github.com/ckan/ckanext-harvest/pull/395

Upgrade to the latest ckanext-harvest

---

Jenkinsfile

This adds building a docker image as part of the build process and pushing to docker hub for each branch. It then tags a release image when a master build completes.
This uses tasks set up in https://github.com/alphagov/govuk-jenkinslib/blob/dab23c591306d9f497f1c89651f7b7c0c6cc6967/vars/govuk.groovy

Add docker tasks to Jenkinsfile

---

ckanext/datagovuk/public/datagovuk.css

https://trello.com/c/dHORr1pB/153-mobile-view-fix-breadcrumbs
Overrides the white-on-white setting on the breadcrumbs below
678px width screens

Make breadcrumbs visible at mobile screen width

---

ckanext/datagovuk/public/datagovuk.css
ckanext/datagovuk/templates/macros/form.html
ckanext/datagovuk/templates/organization/snippets/organization_form.html
ckanext/datagovuk/templates/package/snippets/package_metadata_fields.html
ckanext/datagovuk/templates/snippets/package_basic_fields.html
ckanext/datagovuk/templates/snippets/search_form.html
ckanext/datagovuk/templates/source/new_source_form.html

https://trello.com/c/y5ydUEZx/12-fix-style-issues-on-ckan-publisher-for-28-first-pass
This PR contains a number of frontend tweaks to layouts brought into the views on the upgrade, in order to make the site more legible and a better match against the previous (live) version.
This has involved cloning templates into the extension where necessary, adding required CSS classes throughout templates and doing some style overrides in the custom CSS file.
Some sample screens as they stand now:

Form upgrades

---

ckanext/datagovuk/public/datagovuk.css
ckanext/datagovuk/templates/user/snippets/login_form.html

https://trello.com/c/i0T7TI7h/149-ie-invisible-remember-me-checkbox
Adding layout divs and padding to align the remember checkbox
with other fields, maintains parity with last version and
ensures the checkbox is visible on IE

Re-align remember me checkbox

---

ckanext/datagovuk/templates/source/new_source_form.html

Sets the submit button element to be an actual `button` html element instead of an `input` on the new harvest source form (/harvest/new).
This is part of the work developing the [datagovuk visual regression testing framework](https://github.com/alphagov/datagovuk-visual-regression-tests). Correcting this one inconsistency is going to reduce the work required to make tests run effectively and keep the code as tidy as possible.

Set the submit button for the new harvest source form to be a button element

---

ckanext/datagovuk/public/datagovuk.css

https://trello.com/c/9hveurqU/150-ie-source-type-label-positioning
This explicitly sets a margin of 0 as without it IE collapses the parent
label into the radio button.

Fix IE layout with margin

---

ckanext/datagovuk/controllers/user.py
ckanext/datagovuk/tests/test_user.py

Although the registration form has been replaced, it was still possible to do a POST on the /user/register endpoint to create a user.
https://trello.com/c/7HEtFQiE/2010-3-investigate-and-fix-account-creation-disabled-but-not-really

Block POSTs on user/register

---

bin/install-dependencies.sh

This harvest commit introduces the ability to add a timeout for harvest jobs and will also stop fetches running on harvest objects if the job has been marked as `Finished`.
https://github.com/alphagov/ckanext-harvest/commits/master
https://trello.com/c/yImZoI8P/1824-5-add-a-timeout-for-long-running-harvest-jobs-%F0%9F%8D%90

Update dependencies for harvest

---

ckanext/datagovuk/public/datagovuk.css
ckanext/datagovuk/templates/source/new_source_form.html

https://trello.com/c/mgX7eAdl/168-harvest-source-delete-button-broken
The delete button on harvests should reveal two different delete options
when clicked, but is failing due to the implementation using a hash symbol
in the button link's href. This removes the hash and then adds styles to
give the dropdown options space on screen when it is clicked.
It seems the main issue is caused by some level of clash introduced between certain versions of bootstrap and jquery (see bug reports in the wild such as this: https://www.drupal.org/project/bootstrap_mint/issues/2957269)  and the bug reached beyond our own extension. Luckily the fix is extremely simple (remove the #) within a template we already override. 
Before the fix the delete button jumps the user to the top of the screen and does …

Fix button dropdown

---

bin/python_scripts/find_invalid_tags.py

Add a script which finds invalid tags.
Shows the invalid tags, number of datasets using the tag and the validation error message.
This will be a one off script to help inform the next action to take with tags and the output file should be able to feed into the actual tag cleaning process.
https://trello.com/c/YJGBqhLv/2016-investigate-impact-of-restoring-defaults-schema-to-spatial-tags

Add script to find invalid tags

---

bin/install-dependencies.sh
ckanext/datagovuk/controllers/user.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/action/test_update.py
ckanext/datagovuk/tests/test_ckan_patches.py
ckanext/datagovuk/tests/test_healthcheck.py
ckanext/datagovuk/tests/test_paths.py
ckanext/datagovuk/tests/test_user.py
ckanext/datagovuk/views/healthcheck.py
ckanext/datagovuk/views/user.py

https://trello.com/c/S78qrTJA
I've separated this up into a number of commits to try and make it make sense, so I suggest looking at the commit comments.
Some modifications have been ported, some have been found to be unnecessary.
I've tried to add test coverage to every modification I ported across, and hopefully add some tests to prove the unneccesary ...ness of thing's I've removed.
Still to do: api endpoint modification porting. Then we should be able to remove `before_map()` entirely.

convert user controller modifications to flask views

---

ckanext/datagovuk/templates/package/snippets/package_basic_fields.html

Adds bootstrap column classes to the label and input elements for the status form fields.
**Card:** https://trello.com/c/87ABxr5Q/198-add-data-state-bug

Fix status field width

---

ckanext/datagovuk/templates/user/edit_user_form.html

Removes the class `form-horizontal` from the form tag on the user management view (/user/edit[username]).
There are several styles associated with `.form-horizontal` and other form elements and tags that result in a slightly different display for users. Removing this class ensures that it looks and behaves like other forms across the site.
**Card:** https://trello.com/c/xySUeU3d/197-user-management-page-form-positioning

Minor styling tweak on user management form

---

bin/install-dependencies.sh

Spatial update validates tags to prevent invalid tags from being ingested.
Also update CKAN to 2.7.7.

Deploy spatial sha and upgrade CKAN to 2.7.7

---

Jenkinsfile

7 and 8 are being used for ckan 2.8 branch testing and have a different solr setup.

Jenkinsfile: ban jenkins agents 7 and 8 from running tests for this branch

---

Jenkinsfile
bin/install-dependencies.sh
bin/jenkins-tests.sh
test-jenkins.ini

~This should eventually be the PR that fixes jenkins ci for the `master-2.8` branch. It is nowhere near ready yet, but I need to create a PR to be able to poke jenkins from.~
https://trello.com/c/zLLNaKtv
This allows our `master-2.8` branch to have CI tests pass. To do this I needed to change the setup of solr on some of the CI agents (`ci-agent-7` and `ci-agent-8`). This PR restricts this branch to running on those machines. It also changes the way the tests handle/expect resources to be set up on the agent's database and solr instance. Rather than expecting a single, fixed database/solr core (which caused various problems and potentially would have prevented simultaneous ci runs), it now creates a uniquely named postgres database and solr core before each run and removes them …

Fix jenkins CI for master-2.8

---

bin/jenkins-tests.sh

This is probably just because it doesn't exist. that's fine.
This is a non-ideal way of handling resource setup anyway, and is replaced in our 2.8 branch. Fix this up temporarily in the 2.7 branch for now, because `master`'s CI is currently failing.

jenkins test setup: don't fail if ckan_test db can't be dropped

---

bin/install-dependencies.sh

Upgrade CKAN to 2.7.8 for a number of fixes and also to fix the release to a particular ckan sha.

Upgrade CKAN 2.7.8 to add a number of fixes

---

bin/install-dependencies.sh

https://trello.com/c/OxoHouSW
Otherwise pip is liable to prompt us for interactive input choosing an action, which is bad in a scripted scenario.
This choice should work reliably enough on remote installations yet shouldn't be too eager to overwrite a repo which a developer may have made local changes to (the `wipe` option risks doing this).

install-dependencies.sh: specify --exists-action in pip calls

---

bin/install-dependencies.sh

Reverts alphagov/ckanext-datagovuk#437
Handling of PII was broken due to the way that extras were being output, this affects API calls from Publish app which will mean that Find will not be in sync with CKAN data until the revert or pii_helper code is updated to handle the change in data format.
No longer - 
```
"extras": {
"foi-email": "test-foi@example.com",
"contact-name": "Test User",
"contact-email": "test@example.com"
},
```
but 
```
"extras": [
{
"key": u 'foi-email',
"value": "test-foi@example.com"
},
{
"key": u 'contact-name',
"value": "Test User"
},
{
"key": u 'contact-email',
"value": "test@example.com"
}
],
```

Revert "Upgrade CKAN 2.7.8 to add a number of fixes"

---

ckanext/datagovuk/public/datagovuk.css

Add height attribute for inputs explicitly specifying their height.
On IE11, firefox and opera, input fields don't respect line height so you need to apply an explicit height attribute (see here https://joshnh.com/weblog/line-height-doesnt-work-as-expected-on-inputs/).
**Card:** https://trello.com/c/65KpXkRC/151-ie-slug-field-height

Fix slug preview field height on IE11

---

bin/python_scripts/find_invalid_tags.py
bin/python_scripts/remove_invalid_tags.py

An update of the find_invalid_tags script to add information about the error message so that it can be used when running the remove_invalid_tags script to report to admin users that an invalid tag has been detected in a harvest source.
Also add the remove_invalid_tags script to remove the invalid tags based on the csv output from find_invalid_tags script
https://trello.com/c/pTkZmAPW/2008-3-remove-invalid-tags-from-ckan-database

Add remove_invalid_tags python script

---

ckanext/datagovuk/plugin.py

Prevent Sentry errors from being sent on Integration, as it is being used for reindexing which is throwing up lots of errors and Integration is often used to try things out which potentially will throw errors. 
As Sentry is rate limited these errors will cause other apps in govuk to not have their errors shown.
https://trello.com/c/R4BTJDZy/249-stop-errors-from-reindexing-reaching-sentry-on-integration

Don't send events to Sentry on Integration / local

---

bin/python_scripts/remove_invalid_tags.py

A few bugs fixed to read the CSV as binary to avoid encoding issues and add in the subprocess to call the solr reindex, as it wasn't being called.

Fix bugs in remove_invalid_tags script

---

ckanext/datagovuk/plugin.py

Temporarily prevent errors being sent as reindexing could cause a large number of errors as it did on Integration
The errors caused the rate limit to be hit which meant that other govuk app errors were not visible.

Temporarily prevent Sentry errors from Staging

---

README.rst
bin/install-dependencies.sh
ckanext/datagovuk/plugin.py
ckanext/datagovuk/schema.py
ckanext/datagovuk/tests/test_package.py
requirements.txt

https://trello.com/c/r2q5qNr8/
Solr6+ limits fields of type `StrField` to a length of ~32k, but ckan's `schema.xml` has a catchall field which will add unmentioned fields as `StrFields`. This means we can only afford to have strings greater than 32k under keys we're pretty sure the schema has `TextFields` for. Take this list of "safe" field name patterns from the `ckan28` schema as @ https://github.com/alphagov/govuk-puppet/blob/a927fcdf8210bfb4f810ca619a0c4df9fcde425a/modules/govuk_solr6/files/ckan28.schema.xml
Also bump `ckanext-spatial` version to that matching `master`.

DatagovukPlugin: add before_index method

---

ckanext/datagovuk/public/datagovuk.css
ckanext/datagovuk/templates/page.html

Adds an alert banner that appears on all pages of ckan with the following message:
> There will be a publishing freeze from 06:30am on 27 August to 11:59pm to 28 August. You won't be able to publish, edit or delete datasets while we upgrade the data publishing tool.
There will not be any downtime for visitors – only publishing will be affected.
This alert banner uses [the bootstrap alert warning component](https://getbootstrap.com/docs/4.0/components/alerts/).
What it looks like:
This is to alert users that ckan will be down next Thursday (27th August) whilst the DGU upgrade team move ckan from 2.7 to 2.8.
**Card:** https://trello.com/c/0VQ2mvRX/262-add-a-banner-for-advanced-warning-of-downtime

Add alert banner to all pages

---

ckanext/datagovuk/lib/cli.py

It's possible that sometimes harvest jobs and objects are not cleared out properly when a harvest job is run, so to remove the harvest source additional DB code is needed to remove jobs and objects before the source can be removed.

Also remove test harvest objects and jobs from test data

---

ckanext/datagovuk/templates/page.html

Make it clearer that CKAN is unavailable but data.gov.uk is still working as normal.

Update alert banner to make it clearer

---

ckanext/datagovuk/plugin.py

Lots of jobs have timed out due to upgrading taking more than 12 hours, so ignore sentry errors for now

Temporarily disable sentry during upgrade

---

ckanext/datagovuk/templates/page.html

Remove the alert banner now that the CKAN upgrade has finished.
https://trello.com/c/Ploo4Bxt/267-considerations-for-28-deployment-to-production

Remove upgrade alert banner

---

Jenkinsfile

Allow deployment to run on all agents except agent 4.
Avoid agent 4 as it has been reserved for postgres and will fail the tests.

Run CI on all agents except 4

---

ckanext/datagovuk/plugin.py

Reverts alphagov/ckanext-datagovuk#496
Errors are coming through as some object IDs cannot be found, this might be due to the data sync.
For now lets revert and investigate the issue, I have grabbed a number of IDs to investigate the issue and will try to find a work around to prevent lots of sentry errors being generated.

Revert "Allow Sentry errors for Staging and Production"

---

ckanext/datagovuk/plugin.py

Just enable sentry on production as Staging is prone to errors where it can't find the harvest object id, this might be due to the overnight data sync. 
Logs on production do not have the error so these sentry errors would not appear.
https://trello.com/c/ssYoWQnK/254-considerations-for-28-deployment-to-staging

Allow sentry errors on production

---

ckanext/datagovuk/plugin.py

Reverts alphagov/ckanext-datagovuk#498
Sentry is being sent lots of errors to do with data issues, so for now revert to not send these kinds of errors and investigate the issue as otherwise the errors will cause Sentry to be rate limited preventing other apps from reporting errors.
https://trello.com/c/xLnwdSng/274-investigate-errors-in-sentry-and-prevent-unnecessary-ones-from-being-pushed-up

Revert "Allow sentry errors on production"

---

ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/test_plugin.py

Re-enable sentry errors for Staging and Production but as data errors are already reported to publishers, pushing these errors up to Sentry will cause the rate limit to be hit preventing other apps from reporting errors. So prevent them from being sent to Sentry as they are already recorded else where and presented to the publishers.
https://trello.com/c/xLnwdSng/274-investigate-errors-in-sentry-and-prevent-unnecessary-ones-from-being-pushed-up

Don't push data errors up to Sentry

---

ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/test_plugin.py

`Harvest object does not exist` is being sent to Sentry when we can ignore it as its an issue with the data sync between production and staging.

Ignore harvest object does not exist error

---

bin/install-dependencies.sh

The commit hash is different because it represents a merge commit with upstream, but apart from that it should be on the same version as the official ckan version.
[Trello Card](https://trello.com/c/SlEIlfPl/2149-8-restrict-number-of-jobs-shown-for-harvest-jobs-list-to-100)

Switch to alphagov ckanext-harvest

---

ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/test_plugin.py

Ignore errors where CSW identifier is already used being sent to Sentry as users will already have been informed in their harvest logs and it is more likely a data issue rather than a system error.

Ignore CSW identifier already used: Spatial plugin

---

ckanext/datagovuk/ckan_patches/query.py
ckanext/datagovuk/tests/test_ckan_patches.py

Will convert characters to unicode and ignores characters which can't be converted but as the args will be passed on unchanged this shouldn't affect subsequent processing.

Handle ascii when filtering query

---

ckanext/datagovuk/templates/organization/snippets/organization_form.html

Removes the image upload field from the create publisher and edit publisher views.
Upon investigation, it was discovered that the uploaded image from this upload field isn't utilised anywhere within ckan. Additionally, it was discovered that these upload fields are a potential security vulnerability and should be removed where possible.
[Card](https://trello.com/c/Kfcpv9g1/280-remove-upload-image-on-publisher)

Remove upload field from new publisher page

---

ckanext/datagovuk/public/datagovuk.css

Amend the styling of navigation item highlighting. Specifically:
- Add a `/` to the end of the `href` selector on navigation links
- Remove some styles that are no longer necessary
During the upgrade from 2.8 to 2.9, the links between sections in the ckan UI changed to include a trailing slash on the links. This broke the styling we currently have for links that are specified via the `href`. This feature is useful to communicate to users where they are within the ckan service.
This level of specificity in our CSS is less than ideal, however we aren't in full control of this setup as the navigation is handled within ckan (not this extension).
I removed the additional calls to `li.active a` as I don't envision a situation where we would ever have 2 "active" `li`'s at any one time. We also …

Update styling of active navigation items

---

ckanext/datagovuk/public/datagovuk.css

Adds an override CSS definition for selector `. activity .item .date` with attribute `white-space: normal`.
In ckan's default CSS, the above selector's `white-space` attribute is set to `no-wrap`. This results in the `date` section on the ckan dashboard view to act unpredictably on mobile screen sizes, either flowing off the page or resizing the page. This change ensures that the element flows onto the next line, avoiding unnecessary scrolling or visual bugs for the user.

Fix minor visual bug on ckan dashboard

---

bin/install-dependencies.sh

Use a branch of Spatial https://github.com/alphagov/ckanext-spatial/tree/log-calls which in turn uses a forked repo https://github.com/alphagov/Autologging/tree/only_trace_calls which has been adapted to only trace calls.
As the logging will be temporary it shouldn't be necessary to merge the additional logging into Spatial master. 
The logging has been tested on my local dev stack and it appears to be working.
https://trello.com/c/ayNNNyB2/2329-add-logging-to-trace-calls-in-ckanext-spatial

Update spatial sha to log calls

---

bin/install-dependencies.sh

Some classes were producing too much logging and I've identified some other classes which would be useful to trace
The logging has been simplified in the AutoLogging fork used by the spatial extension as it was inflated by the args passed into the functions which can be quite large.
https://trello.com/c/ayNNNyB2/2329-add-logging-to-trace-calls-in-ckanext-spatial

Update spatial sha in install_dependencies

---

Jenkinsfile
bin/install-dependencies.sh
ckanext/datagovuk/helpers.py
ckanext/datagovuk/tests/test_helpers.py

Add platform performance topics (themes) so that platform performance datasets can be tagged and easily found in the Find app.
https://trello.com/c/NCq4ylTw/2367-3-add-topics-on-dgu-for-performance-platform

Add performance platform topics

---

bin/install-dependencies.sh

Use the latest alphagov spatial sha as we no longer need the additional logging to identify code paths.

Update install_dependencies to use latest spatial

---

ckanext/datagovuk/forms/publisher.py
ckanext/datagovuk/pii_helpers.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/views/dataset.py
tests/test_pii_helpers.py
tests/test_views.py

Updates the PII helpers test as the response has changed slightly with the dropping of V1 API endpoint, the default is now V3. 
Revision ID has also been removed as it has been deprecated for a while and now completely removed from CKAN 2.9
https://trello.com/c/iq6oz3CT/2412-investigate-why-ckan-api-response-extras-block-removed-and-fix-or-document-it

Update search dataset 2.9

---

Jenkinsfile

Add the target branch 'main' param to pushTag and rename dockerTagMasterBranch to dockerTagBranch to fix the creation of release tags.

Fix release tag for main branch

---

bin/install-dependencies.sh

Use the latest alphagov ckanext-spatial sha rather than the sha which traces commands as the tracing is no longer needed and maybe slowing down harvesting.

Use latest alphagov ckanext-spatial sha

---

migrations/004_resolve_harvest_source_types.sql

Update redundant source_types to allow the harvest sources to harvest data with the correct source type.
https://trello.com/c/AUbPYGVo/2534-update-redundant-harvest-source-types
https://trello.com/c/Y1dgeI2i/1130-dgu-harvesters-have-incorrect-source-type

Add sql script to update redundant source_types

---

ckanext/datagovuk/plugin.py
ckanext/datagovuk/tests/test_plugin.py

The exception is most likely on the publisher end, and they already get error logs about them on their harvest dashboard so we don't need to report it to sentry.
https://trello.com/c/yjZQ0yBk/2557-investigate-and-fix-sentry-errors

Ignore exceptions during import

---

Jenkinsfile

Skip deployments from `main` branch which are CKAN 2.8 releases so that deployments of CKAN 2.9 can be deployed from `main-2.9` branch.
https://trello.com/c/GZP41t9N/2553-deploy-ckan-29-onto-integration

Only deploy main-2.9 branch to Integration

---

ckanext/datagovuk/templates/page.html

Show a banner to publishers to forewarn them about downtime to CKAN due to major upgrade work.
https://trello.com/c/kNnlbSBh/2598-create-banner-and-email-for-scheduled-downtime-for-upgrade

Add banner to warn users of downtime next week

---

ckanext/datagovuk/templates/page.html

The downtime has been delayed, so we need to update the banner.
[Trello card](https://trello.com/c/4JYtAux6)

Update downtime notice dates

---

ckanext/datagovuk/action/create.py
ckanext/datagovuk/lib/organogram_xls_splitter.py
ckanext/datagovuk/upload.py
tests/action/test_create.py

CKAN 2.9 changed the way it handles uploads, using `werkzeug.datastructures.FileStorage` which is different from how it was on CKAN 2.8. So this PR updates the way it handles the upload and fixes the tests to reflect the change.
https://trello.com/c/Ia8weJBu/2612-fix-organograms-on-ckan-29

Update organogram file handling for 2.9

---

bin/install-dependencies.sh

This [incorporates](https://github.com/ckan/ckanext-harvest/compare/d939cd1a7d767af16816310d8d954d33e2b79c7c...alphagov:ba53566fb51d6d860b2a1c36b46fe9ebe2cf53b3?expand=1) [a bug fix](https://github.com/ckan/ckanext-harvest/issues/420) which stops duplicated harvest objects being added to Redis. We believe this caused Redis to run out of memory.

Change SHA for ckanext-harvest

---

Jenkinsfile

`ckan29` isn't available for deployment downstream in puppet so use the updated `ckan` app which is now configured to use python 3 instead. This will also fix the problem of the release version check in puppet which would have needed to be reset for `ckan29`.
https://trello.com/c/DZJFi8z5/2613-create-prs-to-prep-for-29-upgrade

Update Jenkinsfile to use ckan not ckan29

---

ckanext/datagovuk/templates/page.html

After the upgrade we no longer need the maintenance banner so remove it.
https://trello.com/c/7HPu6jyN/2647-deployment-of-ckan-29-steps

Remove maintenance banner after upgrade

---

ckanext/datagovuk/plugin.py
tests/test_plugin.py

Re-enable sentry errors after CKAN 2.9 upgrade 
https://trello.com/c/7HPu6jyN/2647-deployment-of-ckan-29-steps

Enable sentry errors

---

bin/install-dependencies.sh

Update the harvest sha to fix harvester `run-test` command and also update dependencies to ensure that `run-test` has the dependencies it needs to run.
The CKAN sha has also been updated to use the CKAN master branch rather than a fork of CKAN now that the database has been updated.
This has been tested on Integration.
https://trello.com/c/7HPu6jyN/2647-deployment-of-ckan-29-steps

Update harvest sha fix run test

---

ckanext/datagovuk/plugin.py
tests/test_plugin.py

Add some more errors which are sent to Sentry which can be ignored as they are due to user data which they are aware of or because of a valid error thrown when a user not found.
https://trello.com/c/EyKpnr3E/2666-ignore-post-ckan-upgrade-sentry-errors

Update sentry errors to ignore

---

ckanext/datagovuk/action/create.py
tests/action/test_create.py
tests/test_s3_resources_plugin.py
tests/test_upload.py

Only allow publishers to upload XLS files, this should help reduce problems with Organogram CSV files.
https://trello.com/c/UGpKiiOb/2673-some-organograms-dont-render-their-interactive-diagrams

Only allow organogram xls

---

ckanext/datagovuk/plugin.py
tests/test_plugin.py

Ignore auth errors as they are not problems which can be fixed in the code and create noise in sentry which might hide errors which need attention.
https://trello.com/c/bizUat3o/2669-ignore-outstanding-dgu-sentry-errors-based-on-sentry-error-list

Ignore more errors sent to sentry

---

bin/install-dependencies.sh

Update spatial sha to fix XML parsing on spatial harvest datasets.
https://trello.com/c/bizUat3o/2669-ignore-outstanding-dgu-sentry-errors-based-on-sentry-error-list

Update spatial sha to fix gemini2 xslt file path

---

ckanext/datagovuk/plugin.py
tests/test_plugin.py

Stop validation errors from emails reaching sentry as the error is already visible to users and its not a code bug.
https://trello.com/c/bizUat3o/2669-ignore-outstanding-dgu-sentry-errors-based-on-sentry-error-list

Ignore Validation errors from already registered emails

---

bin/install-dependencies.sh
ckanext/datagovuk/upload.py
requirements.txt

Updating the commit sha of ckan extensions besides the datagovuk extension doesn't update the extension properly, so instead force a reinstall which does work. 
https://trello.com/c/wzsJ3luK/2694-fix-upgrade-of-ckan-extensions-during-deployment

Fix deployment of other ckan extensions

---

bin/install-dependencies.sh

The forked CKAN fixes issues around the feed endpoint which was throwing errors due to control characters in the XML.
https://trello.com/c/A7RhW5Ux/2698-investigate-news-feed-dgu-sentry-error

Update CKAN sha to use forked CKAN

---

bin/install-dependencies.sh

Forked CKAN sha has been updated to handle no notes as the default empty '' was not being returned when the notes were not present in the dict.

Update install dependencies CKAN sha

---

ckanext/datagovuk/plugin.py
tests/test_plugin.py

Ignore Group not found errors, we use organizations rather than groups so there would never be any groups to show.

Ignore group 404 as DGU has organizations

---

bin/install-dependencies.sh

Explicitly remove enum34 before installing ckan as it causes problems with the ckan installation.

Make sure enum34 is uninstalled

---

bin/python_scripts/solr_reindex_target_date.py
migrations/005_update_resource_extras.sql

Some legacy resources were using datastore which we is not supported in the current running version of CKAN on DGU and is causing errors in CKAN as the datastore extension is not available. In order to get the resources to be viewable the resource extras field need to be updated and the datasets affected need to be reindexed. 
Both of these need to be run manually on the database and on the CKAN machine. 
This has been tested on Integration.
https://trello.com/c/tJdgAiao/2696-investigate-cause-of-build-errors-in-dgu-sentry

Fix resources which were using datastore settings

---

bin/install-dependencies.sh
ckanext/datagovuk/plugin.py
tests/test_plugin.py

After looking at some logs which detailed the user which was trying to access the datasets it is clear that the dataset is not accessible by the user because it has been deleted. Which is why initially there is a user permissions error as sysadmins can still view the dataset but other users will get a 404 response.
So it is safe to ignore the error in Sentry,
https://trello.com/c/De5AG7yb/2703-investigate-cause-of-user-permissions-errors-on-datasets-reads

Ignore 404 dataset

---

bin/install-dependencies.sh

The harvest sha linked to ignores redis items with an empty body as this was causing an exception when trying to set it in Redis.
This is the commit linked to - 
https://github.com/alphagov/ckanext-harvest/commit/f52605c9a4f8ccaa0f5e83937c59ce9bf58cbc06
https://trello.com/c/tlYrmfIV/2695-investigate-cause-of-redis-errors-appearing-in-dgu-sentry

Update harvest sha to fix redis errors

---

ckanext/datagovuk/plugin.py
tests/test_plugin.py

404s are occurring for some resources because they are in a deleted state so do not send them to sentry as it is not a problem with code.
This is similar to how 404s for deleted datasets are being handled.

Prevent 404 on resource being sent to Sentry

---

ckanext/datagovuk/ckan_patches/cli.py
ckanext/datagovuk/plugin.py
ckanext/datagovuk/upload.py
tests/test_ckan_patches.py
tests/test_plugin.py

Users are unable to change their passwords because their Usernames are not valid when using the default CKAN user schema, so relax the user schema by monkey patching it.
Also prevent organogram errors from reaching sentry as its an error that can be handled by the user and fix a bug in making the organogram filenames lowercase.
https://trello.com/c/alHbD02j/2705-users-cannot-change-their-ckan-password

Fix users password reset by relaxing the username schema

---

ckanext/datagovuk/templates/page.html

Remove the maintenance banner after the upgrade has complete.
https://trello.com/c/lkdK9QM2/71-do-the-postgres-upgrade-for-ckan

Remove maintenance banner

---

bin/install-dependencies.sh

Updates to use latest version of alphagov/ckanext-spatial, with validation fixes for Gemini 2.3 Schemas.

Update ckan spatial dependency

---

.github/workflows/ci.yml
tests/test_package.py

Add github actions test to enable external users to upload changes to organogram test files.
https://trello.com/c/QAq4fYIX/918-add-ci-tests-to-github-actions-for-ckanext-datagovuk

Add ci test

---

.github/workflows/ci.yml
bin/install-dependencies.sh

Update organogram files to fix a validation bug when the profession field was left blank, it should be possible to do this but the validation was previously not allowing it to pass.
In addition pre-formatted rows for junior roles have been increased to 23,000 rows.

Update organograms swp

---

Jenkinsfile
Procfile
bin/install-dependencies.sh
requirements.txt

Upgrade of CKAN to 2.9.7 to resolve a security vulnerability
https://trello.com/c/ouCltnih/1595-handle-ckan-user-security-vulnerability

Upgrade CKAN to 2.9.7

---

bin/install-dependencies.sh

Update the alphagov for of CKAN with the user security patch cherry picked from this commit https://github.com/alphagov/ckan/commit/885f9e0b668e3496a8f2c0c0a9f1cb59bf810e16
https://trello.com/c/ouCltnih/1595-handle-ckan-user-security-vulnerability

Update install-dependencies to use CKAN patch

---

ckanext/datagovuk/lib/organogram_xls_splitter.py

Sorting of mixed types causes an internal error so don't convert strings to ints.

Fix sorting of refs in organograms

---

bin/python_scripts/solr_reindex_target_date.py
ckanext/datagovuk/lib/cli.py
migrations/006_set_duplicate_datasets_deleted

Add a CLI command to just reindex recent datasets, default is set to 24 hours before now, otherwise can set an env var to adjust the timeframe. 
Also update the solr_reindex_target_date script to handle reindexing of datasets with different states and add the DB script to set duplicate datasets to a deleted state where they have a harvest object which is not the current one.
https://trello.com/c/5LSihxlF/1139-investigate-and-fix-duplicate-datasets
https://trello.com/c/CxQutDOt/1115-update-ckan-helm-chart-to-run-on-integration-cluster

Add cmd reindex recent datasets

---

docker/ckan/Dockerfile
docker/pycsw/Dockerfile

Update the spatial shas to improve pycsw load process so that it only processes the last 12 hours metadata_modified difference and not everything.
https://trello.com/c/GnDhUN6u/1140-improve-solr-reindexing-and-pycsw-loads-efficiency

Update dockerfiles to use latest spatial sha

---

ckanext/datagovuk/lib/cli.py

Improve the output from the redindex_recent command to make it easier to look at logs to check that it is functioning.
https://trello.com/c/GnDhUN6u/1140-improve-solr-reindexing-and-pycsw-load-efficiency

Improve the output from reindex_recent

---

docker/ckan/Dockerfile
docker/pycsw/Dockerfile

Reverts alphagov/ckanext-datagovuk#1281
pycsw compares the datasets entire list to the records in the pycsw database so need to fetch all datasets and not just those modified in past 12 hours
https://trello.com/c/GnDhUN6u/1140-improve-solr-reindexing-and-pycsw-load-efficiency

Revert "Update dockerfiles to use latest spatial sha"

---

.github/workflows/ci.yml
bin/install-dependencies.sh
ckanext/datagovuk/plugin.py
ckanext/datagovuk/views/metrics.py
docker/ckan/Dockerfile
docker/pycsw/Dockerfile
requirements.txt

Note that prometheus-flask-exporter needs to be installed as part of CKAN otherwise datagovuk assets are not loaded by CKAN framework.
This is currently done in the CKAN and pycsw Dockerfiles
https://trello.com/c/KPzUKkgY/1146-add-metrics-to-ckan

Add prometheus metrics endpoint

---

bin/setup_pycsw.sh
ckanext/datagovuk/plugin.py
docker/ckan/Dockerfile

Exclude /healthcheck from metrics and 
- fix bug in the pycsw script to run instead on CKAN database
- Set the WORKDIR to CKAN to make it easier to run a WSGI server
https://trello.com/c/GLNeQrpL/1148-use-wsgi-server-rather-than-flask-dev-server

Do not run metrics on /healthcheck endpoint

---

bin/install-dependencies.sh

Use the latest spatial commit to increase timeout for getting content to 20 seconds
Spatial commit used -
https://github.com/alphagov/ckanext-spatial/commit/ee6c67f6a28dbe524e0ffac068a3087ede3afbb5

Update install-dependencies latest spatial

---

.github/workflows/ghcr.yaml

This functionality doesn't work since the build needs extra parameters that this trigger doesn't support, so it always fails.

Disable building images on schedule

---

.github/workflows/ghcr.yaml
docker/ckan/Dockerfile

Pinning zope eventually fixed the issue, so scheduled builds can be restarted.

Update ckan dockerfile

---

docker/build-image.sh

Dockerfile is prefixed with version and not a git sha when building the image from a workflow trigger.

Dockerfile name should have version prefix

---

bin/setup_ckan.sh
docker/build-image.sh
docker/ckan/2.9.9-core.Dockerfile
docker/ckan/2.9.9.Dockerfile
docker/solr/8.Dockerfile

Fix problems with manual build of images on branches used for testing integration deployments. 
Also update solr to use the spatial version and update CKAN to latest 2.9 version to fix search index rebuild problems.

Update ckan 2.9.9

---

bin/install-dependencies.sh
docker/ckan/2.9.3.Dockerfile

Update the CKAN sha to commit that has the email validation fix. 
This should be the least impact on the existing production stack as not sure if upgrading CKAN to 2.9.5 will introduce any other issues, whereas cherry picking the fix in our CKAN fork should fix the email validation issues experienced in 2ndline.
https://trello.com/c/bQjFJgQh/1609-ckan-add-exception-handling-for-email-validation-error

Update 2.9.3 email fix

---

bin/setup_ckan.sh

There's no need to run the db init normally as part of a start up script when connecting to an existing database so only do it for new stacks.

Only run CKAN db init for new stacks

---

docker/create-pr.sh

If the env isn't added, its not possible to create the branch with the same name

Fix create PR on govuk-ckan-charts by adding ENV

---

bin/install-dependencies.sh

Use the following spatial commit sha -
https://github.com/alphagov/ckanext-spatial/commit/3004c0f191831a66cb6b5d1ec6f521e3ff35353c
to fix the setting of csw config to allow publishers to set gemini2.3 as a validation schema

Update spatial sha to fix the csw source config

---

.github/workflows/build-image.yaml
docker/build-image.sh
docker/ckan/2.9.9-base.Dockerfile
docker/ckan/2.9.9.Dockerfile
docker/docker-compose-2.9.3.yml

This PR contains a number of updates - 
- Updates the 2.9.9-base.Dockerfile to use a spatial sha that works with the gemini-csw harvest source.
- Fix the Dockerfiles as they would not have picked up changes in this repo in their previous form.
- Update the build-image.yaml to allow for clearer options for building and pushing images
- Make fixes to the docker-compose-2.9.3.yml in line with updated directory structure

Update dockerfile spatial gemini 2.3

---

docker/create-pr.sh

This should stop the GHA failures due to trying to push commits to an existing branch.

Update create-pr.sh to handle duplicate branches

---

ckanext/datagovuk/templates/page.html

Show the maintenance banner to publishers in case they are not registered as admin users so didn't get the email.
https://trello.com/c/vGRauGZi/1223-setup-maintenance-ckan-banner

Show the publishing freeze maintenance banner

---

docker/ckan/2.9.9-core.Dockerfile

Used a CKAN fork to fix the authenticator as upgrading of CKAN to 2.10 will automatically fix this issue.
https://github.com/alphagov/ckan/commit/b6414dc6374c322e2748dad2464bbc872c8de162
Tested on integration cluster

Use alphgov CKAN fork to fix email login

---

ckanext/datagovuk/plugin.py
docker/create-pr.sh

By default the Flask prometheus exporter groups its metrics by path. This results in a huge number of labels (currently 366,675 series), which makes for expensive queries and is generally not good for a healthy Prometheus.
Try grouping by url_rule, which should cut things down into fewer buckets.
Alternatively, we could group by endpoint, but the metrics currently look like everything is just reported under one "http" endpoint, so that might be too coarse.

Group metrics by url_rule

---

docker/ckan/2.9.9-base.Dockerfile

This will fix the responses presented to publishers on the admin site as currently they show inaccurate information on the status of harvest jobs.

Update spatial sha to fix missing commits

---

.github/workflows/create-pr-on-tags.yaml

Rather than creating the PR for staging and production on tag push, wait for the image to be built before creating the PRs

Update create PR on tags on workflow trigger

---

bin/setup_ckan.sh

This only really affects deployment of a new cluster for local development but its good to fix so that local dev clusters can easily be spun up.

Remove extra square bracket as causes error

---

ckanext/datagovuk/templates/user/edit_user_form.html
ckanext/datagovuk/templates/user/new_user_form.html

Updates the edit_user_form template in line with the upstream branch as it had gotten out of sync. 
The shas next to the commits headings indicate which commit shas the changes originated from in the ckan/ckan repo. 
This makes the update of user profiles by sysadmins a bit clearer and also empowers sysadmins to reactivate users without having to update the user state in the database.
Tested on integration.

Update edit user form for clearer sysadmin UI when managing users

---

docker/ckan/2.9.9.Dockerfile

5.1.1 removes a require attribute _ElementStringResult which is causing problems with some harvest sources using XML.

Pin lxml to < 5.1.1

---

ckanext/datagovuk/action/create.py

This is needed by one of the publishers to import their organogram file

Add mimetype for .xlsm files

---

docker/ckan/2.10.4-base.Dockerfile
docker/pycsw/2.6.1.Dockerfile
requirements.txt

Update the spatial sha for CKAN and pycsw to latest version with passing tests. 
Also update the requirements jinja2 version to fix security vulnerability.

Update spatial sha to latest version with passing tests and update jinja2 requirement

---

README.md

Some additional guidance for running a local docker dev stack.

Update README.rst with info re local dev and GHA

---

migrations/008_remove_harvest_coupled_resource.sql

The harvest_coupled_resource table is preventing the harvest source datasets from being cleared so drop the table as it does not appear to be referenced anywhere in the main CKAN code or any extensions.

Add the migration script for audit purposes, script will be manually run

---

migrations/009_delete_harvest_object_records.sql

This script was needed on production environment, it was possible to run the ckan `harvester source clear` command in other environments without any problems.

Add script used to remove MEDIN harvest source datasets

---

ckanext/datagovuk/lib/organogram_xls_splitter.py

This fixes an issue with organogram uploads reported by HMRC

Use df.loc[index, col] as df[col, index] is being deprecated

---

.github/workflows/build-image.yaml
.github/workflows/ci.yml
docker/build-image.sh
docker/ckan/2.10.4-base.Dockerfile
docker/ckan/2.10.4.Dockerfile

This will allow us to keep previous CKAN base images as well as newer base images in the future by incrementing the patched versions

Update files to allow for patched CKAN base and core dockerfiles

---

.github/workflows/build-image-on-tags.yaml

Without the PATCH env arg the build image won't be correct when releasing to Staging and Production.

Add PATCH env to build-image-on-tags.yaml

---

.github/workflows/build-image-on-tags.yaml

Need the REPO_OWNER env var to determine whether to build the image or not in build-image.sh

Add REPO_OWNER env to build-image-on-tags.yaml

---

.github/workflows/build-image.yaml
.github/workflows/ci.yml
docker/ckan/2.10.4-base.Dockerfile
docker/ckan/2.10.4-core.Dockerfile
docker/ckan/2.10.4.Dockerfile
requirements.txt

Upgrading to python 3.11 should fix iso date format validation issues for fractional seconds reported by a publisher.

Upgrade python 3.11

---

docker/create-pr.sh

The github action appears to error as the latest updates haven't been pulled down but the branch is still created on DGU charts for Integration. Staging and Production branches are unaffected.

Pull down git updates

---

.github/workflows/create-pr.yaml
docker/create-pr.sh

Looks like the issue is that the create-pr task is being called twice, so actually the git pull is not needed and neither is the trigger when pushing to main branch as this is causing the error in Github actions.

Remove git pull from create-pr.sh and remove create PR trigger from pushing to main

---

.github/workflows/build-image-on-tags.yaml
.github/workflows/build-image.yaml
.github/workflows/ci.yml
build-config.yaml
docker/ckan/2.10.4-base.Dockerfile
docker/ckan/2.10.4.Dockerfile
docker/pycsw/2.6.1.Dockerfile

This took quite a bit of work! And sitting and thinking about "how" to make this somewhat maintainable, understandable and also not too repetitive/redundant. Always happy for suggestions, recommendations, constructive criticisms etc.
This creates a new Workflow file for CKAN/DGU builds to create ARM versions of each of the different images. The new workflow tries to do-away with the current `build-image.sh` bash script and move a lot of the logic into the Workflow itself. The hope is that this will make the workflow a little easier to debug if anything goes wrong.
This PR also creates a new `build-config.yaml` file that contains the various app versions, tags and also the "build types" and which apps each of those build types will actually build, using YAML anchors to try and de-duplicate …

Refactor Build Workflow for ARM Build Support

---

migrations/010_reset_os_roads_updated_at.sql

This will ensure that the latest harvest_object_id is set.
The script will have to be run manually as there is no automatic application of these database scripts.

Add SQL script for reseting updated_at value for OS roads

---

.github/workflows/build-image-on-tags.yaml

Hard code the location of build-image.yaml and also allow the building of tagged images to be triggered manually for debug purposes

Hard code the build-image.yaml location as the runner cannot find the file

---

.github/workflows/build-image-on-tags.yaml
.github/workflows/build-image.yaml
build-config.yaml

The image was being tagged with sha rather than version number upon git tag, the gitRef is now being used if it is provided and passed with the build_push_ckan_with_gittag input.

Fix build image on tags

---

.github/workflows/build-image.yaml

This will tag the pycsw image appropriately so that different releases can be referenced.

Add patch to pycsw image tag

---

bin/python_scripts/remove_duplicates.py
build-config.yaml
docker/ckan/2.10.4-base.Dockerfile
docker/ckan/2.10.4.Dockerfile
docker/pycsw/2.6.1.Dockerfile

The script will find all datasets which have more than 100 active datasets from the same publisher with the same title. 
These duplicate datasets come from 2 publishers so limit the deletions to the datasets from these publishers and reindex the latest dataset as it might have failed reindexing before due to a bug in the spatial extension which has been fixed. 
The dataset deletion is handled within CKAN as it will set the dataset state and reindex it rather than removing the datasets in case we need to change the dataset state back to active.

Remove dataset duplicates

---

.github/workflows/build-image.yaml
build-config.yaml
ckanext/datagovuk/ckan_patches/helpers.py
ckanext/datagovuk/plugin.py

The link button styling was encoded causing some confusion with users. 
I had tried to upgrade CKAN but that didn't fix the styling issue and was complicated due to having to fix some dependency issues so for now just monkey patch it with code that works. 
https://github.com/alphagov/ckanext-datagovuk/issues/1871

Fix link icons

---

.github/workflows/ci.yml
build-config.yaml
docker/solr/2.10.Dockerfile

This just bumps the patch version for Solr to "c" so we can have a tagged ARM version available for testing.

Bump Solr to 2.10-c for ARM flavour

---

ckanext/datagovuk/lib/cli.py

If no rows are specified it only retrieves the first 10 which means that lots of duplicates get added to the index

Update reindex_organisations to retrieve 3000 rows for checking existence

---

.github/workflows/ci.yml

Actions cache v2 has started to brownout. We should look to move to the latest version.

⬆️ Bump actions/cache to 4.2.0

---

README.md

- Update the README to clarify the deployment process for Integration, Staging, and Production.
- Include the environment URLs, noting that Integration and Staging require VPN access.
- **README**:
- Added a new **Deploying CKAN** section explaining:
- How to deploy to **Integration** (triggered by merging into `main`, followed by merging a PR in the govuk-dgu-charts repo).
- How to promote the same changes to **Staging** and **Production** by creating a release, which triggers the creation of two further PRs (one per environment).
- Listed environment URLs:
- Integration: [https://www.integration.data.gov.uk](https://www.integration.data.gov.uk) (VPN required)
- Staging: [https://www.staging.data.gov.uk](https://www.staging.data.gov.uk) (VPN required)
- Production: …

♻️ Change the deploy steps in README

---

build-config.yaml
ckanext/datagovuk/lib/organogram_xls_splitter.py

Some publishers were having problems with the organograms but not able to see the all the validation errors. 
This should catch all ValueErrors to report back to the publisher so that they can amend their organogram file.
This has been tested on integration and works as expected.

Catch value error organograms
