ckanext/datagovuk/plugin.py, ckanext/datagovuk/public/datagovuk.css, ckanext/datagovuk/templates/base.html
.. replace with nearly black and green.
Adds the .css for overwriting styles, and the templates folder for changing the structure of pages.
=> Remove some of the blue and gray and ..

ckanext/datagovuk/lib/cli.py, setup.py
Generate a CSV of emails and reset keys so that Notify can be used to send information about resets
=> Adds a paster command to reset all user passwords

bin/travis-build.bash
A number of dependencies in DGU code were missing
https://trello.com/c/lBfcpoyb/285-get-travis-working-for-ckanext-harvest
=> Add ckanext-spatial to the Travis build

ckanext/datagovuk/templates/header.html
https://trello.com/c/TwLQmz1L/243-remove-search-bar-from-header-s
=> Remove the search box from main site header

ckanext/datagovuk/public/datagovuk.css, ckanext/datagovuk/templates/header.html
Takes text from ckan.ini config file
=> Update logo to match DGU Find

ckanext/datagovuk/controllers/organization.py, ckanext/datagovuk/plugin.py
This commit can be reverted when https://github.com/ckan/ckanext-harvest/pull/325 is approved
https://trello.com/c/2AMXSoAx/274-add-harvester-tab-to-organisation-page
=> Bring the harvest_org_list code into ckanext-datagovuk from ckanext-harvest

ckanext/datagovuk/forms/publisher.py, ckanext/datagovuk/plugin.py, ckanext/datagovuk/templates/organization/snippets/organization_form.html, ckanext/datagovuk/templates/package/snippets/package_metadata_fields.html, setup.py
Add contact/FOI fields to the publisher schema and also to the package schema.  Also removes the CKAN default contact/maintainer fields.
https://trello.com/c/7mvApeUY/305-add-correct-contact-fields
=> Add the contact/FOI fields

ckanext/datagovuk/templates/package/snippets/package_metadata_fields.html
https://trello.com/c/1emYm1Et/297-hide-source-field
Removes the source field.
=> Remove source field

ckanext/datagovuk/templates/package/snippets/package_basic_fields.html, ckanext/datagovuk/templates/package/snippets/package_metadata_fields.html
https://trello.com/c/NK7Hloos/295-remove-tags
https://trello.com/c/aef8F73P/298-hide-version-field
=> Remove the version and tag inputs

ckanext/datagovuk/plugin.py, ckanext/datagovuk/templates/package/snippets/resource_form.html
https://trello.com/c/xbOo8Ux5/302-add-date-field-to-datafile-form
=> Add a date field to resource add/edit form

ckanext/datagovuk/templates/package/snippets/package_basic_fields.html, ckanext/datagovuk/templates/package/snippets/resource_form.html, ckanext/datagovuk/templates/source/new_source_form.html
https://trello.com/c/WXZNg1Y1/299-remove-placeholders-from-form-fields
=> Remove placeholder text from form fields

ckanext/datagovuk/templates/package/resources.html
https://trello.com/c/4r6QukwZ/308-remove-reorder-resources-button
=> Remove re-order button

ckanext/datagovuk/templates/organization/edit_base.html
https://trello.com/c/EmWb5gWI/314-remove-datasets-tab-from-manage-publisher
=> Remove datasets tab from manage publisher

IMPORT.md, import/migrate_datasets.py, import/migrate_harvest_sources.py, import/migrate_users.py, import/running_stats.py
datagovuk_ckan_deployment is not checked out in integration, therefore the import scripts are better located in this extension, which will always be available
=> Move the data import scripts from datagovuk_ckan_deployment to ckanext-datagovuk

import/migrate_datasets.py
Import code has moved from datagovuk_ckan_deployment to ckanexta-datagovuk so making the PR here.
Original PR: https://github.com/alphagov/datagovuk_ckan_deployment/pull/55
Trello Card: https://trello.com/c/NK7Hloos/295-remove-tags
=> Remove tags from dataset import

ckanext/datagovuk/controllers/user.py, ckanext/datagovuk/logic/validators.py, ckanext/datagovuk/plugin.py, ckanext/datagovuk/schema.py, ckanext/datagovuk/templates/user/edit_user_form.html, ckanext/datagovuk/templates/user/new_user_form.html, ckanext/datagovuk/templates/user/snippets/password_guidelines.html
- Change the minimum password length in user schema from four characters to eight characters (matches legacy CKAN) and update relevant error message
- Add hint text to explain how to create a stronger password
https://trello.com/c/NzGpQkop/403-increase-password-security-for-ckan
=> Increase password strength

ckanext/datagovuk/templates/package/edit_base.html
https://trello.com/c/sZZSzypf/310-remove-view-button-from-edit-resource
=> Remove 'View Dataset' button from edit dataset page

Jenkinsfile, bin/install-dependencies.sh, bin/jenkins-tests.sh, requirements.txt, test-jenkins.ini
Adds a new test config for our Jenkins configuration,
and a Jenkinsfile and bash script to actually run the
tests. This moves the app closer to GOV.UK development
workflow standards.
=> Build this extension on Jenkins

import/migrate_users.py
Leave it as it was previously, then user can login with either their old username or email address
=> Do not change the username to the user's email address

ckanext/datagovuk/helpers.py, ckanext/datagovuk/plugin.py, ckanext/datagovuk/public/datagovuk.css, ckanext/datagovuk/templates/organization/member_new.html
https://trello.com/c/jpPUupRZ/376-remove-member-role-when-adding-publishers
- Removes "member" as an option for a user when added to an org
- Tidies the form layout
=> Remove "member" role

ckanext/datagovuk/templates/package/resource_edit_base.html
https://trello.com/c/sZZSzypf/310-remove-view-button-from-edit-resource
=> Remove 'View Resource' button from resource edit form

import/migrate_datasets.py
Note: `contact_email` is a CKAN default; `contact-email` is an extra we have added.
=> Cleanse the email addresses

ckanext/datagovuk/templates/user/request_reset.html
https://trello.com/c/cMdZkkAx/363-update-reset-password-message
=> Rename username/email field to email address

ckanext/datagovuk/plugin.py
https://trello.com/c/lAZCtF4A/424-fix-data-import-issues
=> Remove email validator from CKAN core email fields

import/migrate_datasets.py
This key was duplicated in extras and the main schema.  It is promoted to the main schema in this extension.
https://trello.com/c/lAZCtF4A/424-fix-data-import-issues
=> Remove the date_update_future extra

Procfile
$CKAN_INI already exists, so we should use this rather than harcoding the path
=> Tidy Procfile

ckanext/datagovuk/public/publisher-files/Blank_Organogram_Template_latest.xls
https://trello.com/c/0dy6UhIJ/118-move-the-organogram-spreadsheet-template-off-ckan
=> Add public XLS organogram template

bin/install-dependencies.sh, requirements.txt
https://trello.com/c/wc759hKC/42-update-harvesters-to-include-changes-made-recently-on-bytemark#comment-5c0a7354e889e0278c34beb9
=>  Switch CKAN spatial to alphagov fork

ckanext/datagovuk/logic/validators.py, ckanext/datagovuk/plugin.py
https://trello.com/c/BATbGtvS/742-some-schema-validation-issue-blocking-publishing-of-data-files-something-wrong-with-the-package-or-resource-extras
=> Better schema key error

bin/install-dependencies.sh
https://trello.com/c/Qb7SyPRK/782-investigate-rolling-back-dgu-ckan-harvester-to-previous-harvesters-to-see-if-that-helps-in-the-short-term-to-fix-the-user-report
=> Update spatial harvester to include CSW fixes

bin/install-dependencies.sh
It has a fix for the plugin making the process crash.
=> Update to the latest spatial plugin

bin/install-dependencies.sh
https://github.com/alphagov/ckanext-spatial/pull/6
=> Update spatial plugin

bin/install-dependencies.sh
This PR contains the commit to upgrade the harvest sha as well as the DCAT sha
=> Update dcat to alphagov 6253f29

bin/install-dependencies.sh
Includes https://github.com/alphagov/ckanext-harvest/pull/5.
=> Update to the latest version of ckanext-harvest

ckanext/datagovuk/action/create.py, ckanext/datagovuk/tests/action/test_create.py
We have made the following changes to ensure files uploaded to S3
have consistent naming and display the visualisations properly:
- the current date timestamp is included at the beginning of the
filename
- the user can provide a date, if this is not specified it will
default to todays date and is included as part of the filename
and name of the dataset. This makes it easier to distinguish between
several resources in the same dataset
- removed `post` from the file name as it expects the filename to
end in `-junior.csv` and `senior.csv`
Part of https://github.com/alphagov/ckanext-s3-resources/pull/2
Paired with @kentsanggds 
Trello card: https://trello.com/c/5KrmZ1tb/1025-fix-bug-to-show-visualisation-on-junior-post-organograms
=> Add fixes to enable junior post visualisations

bin/install-dependencies.sh
User commit from `ckanext-s3-resources` to lowercase s3 filenames.
=> Update to use commit from s3 filenames to lower case them

ckanext/datagovuk/helpers.py, ckanext/datagovuk/plugin.py, ckanext/datagovuk/templates/package/snippets/resource_form.html
- also remove format as not needed on the upload page for central gov organograms
=> Update resource_form.html to add help on organograms

ckanext/datagovuk/templates/package/snippets/resource_form.html
Location of organogram guidance for central government looked odd on deployed stack and behaved differently from local dev stack so have simplified it.
=> Update organogram extra help style resource_form

bin/install-dependencies.sh
- harvest commit contains update to comment out long running queries that cause time outs so will allow the harvest_source list to be fetched for harvesting purposes by UKMDE
=> Update harvest_sha to 4071fa

bin/python_scripts/remove_march2019_duplicates.py
The script wasn't working on staging because the script was not picking up the argument. 
The script has been updated and tested on a local dev stack to make sure that it uses the filter.
=> Fix the script when date filters are added

bin/python_scripts/remove_march2019_duplicates.py
After running the script on staging, a number of things came up which should help improve the script by narrowing the datasets affected to only those with metadata dates matching and adds some numbering so that the dev can keep track of the processing.
- also added a feature to allow for reindexing of SOLR targetting datasets as otherwise the reindexing can take 30 minutes or more when rolling back.
=> Update the script which finds duplicate datasets

bin/jenkins-tests.sh
Rather than just ignoring failed commands.
=> Fail fast in jenkins-tests.sh

bin/install-dependencies.sh
This update uses a commit for the harvest branch which will be merged upstream.
=> Update harvest sha to add upstream commits

bin/python_scripts/solr_reindex_target_date.py
Update the reindex command to use --config as -c doesn't work.
Also optimise the code to target active datasets and provide some progress output to user.
=> Update the solr reindex command to use --config

ckanext/datagovuk/pii_helpers.py, ckanext/datagovuk/tests/test_pii_helpers.py
Remove author and author email from api/search/dataset endpoint and update the tests for pii_helper
=> rm author and author_email from api/search/dataset

bin/install-dependencies.sh
Use latest harvest commit to fix issues with harvest force-import
=> Update dependencies for harvest

ckanext/datagovuk/plugin.py
We were handling the `/api/search/dataset` endpoint but not the `/api/3/search/dataset` endpoint , so this commit will also handle that.
=> Process api/3 endpoint to remove PII info

ckanext/datagovuk/templates/user/dashboard.html
https://trello.com/c/e43yK9AF
Pretty straightforward.
=> user dashboard template: update to work with ckan 2.8

bin/install-dependencies.sh, bin/python_scripts/find_invalid_tags.py
Export the invalid tags with enough information to restore them if they are needed to be restored.
https://trello.com/c/oMXOxBxc/2031-export-invalid-tags-with-their-associated-package
=> Export invalid tag data to csv file

bin/install-dependencies.sh
https://trello.com/c/OxoHouSW
Looks like we need something stronger for integration - "switch" doesn't properly switch the repo over to the new contents. This does.
=> bin/install-dependencies.sh: switch --exists-action to "b", backup

ckanext/datagovuk/plugin.py
Stop sentry logs on Integration and local development machines.
Sentry is rate limited, due to the large number of errors from Integration due to data issues when reindexing this is causing problems with other govuk apps sending errors to Sentry.
https://trello.com/c/R4BTJDZy/249-stop-errors-from-reindexing-reaching-sentry-on-integration
=> Don't send events to Sentry on Integration / local

bin/python_scripts/solr_reindex_package_ids.py
Target solr reindex to problem datasets.
=> Script to reindex solr using a list of package ids

README.rst, ckanext/datagovuk/lib/cli.py, setup.py
To be able to run the CKAN functional tests we need to create test data, this can be done manually but it can take about 30 minutes to set it up and there's a chance that mistakes are made. Making it automated will make it easier to run the CKAN functional tests quickly.
https://trello.com/c/v7jpDYro/166-automate-creation-of-test-publisher-and-harvest-source
=> Setup test data

README.rst, ckanext/datagovuk/lib/cli.py, setup.py
Set the correct static mock harvest source when running on different docker ckan versions.
Also add in the commands for creating and removing test data.
=> Update test data mock harvest source

ckanext/datagovuk/templates/home/layout.html
I added this in during a presentation of the VRT and somehow it made it's way into the codebase 🤦
=> Remove bad content from homepage

bin/install-dependencies.sh
Harvest workers were sending single character ids to be re-queued, this commit fixes it.
=> Update to latest harvest sha to fix requeuing objs

ckanext/datagovuk/plugin.py
Allow sentry errors now that the upgrade is complete and the Staging and Prod environments are stable.
https://trello.com/c/ssYoWQnK/254-considerations-for-28-deployment-to-staging
https://trello.com/c/Ploo4Bxt/267-considerations-for-28-deployment-to-production
=> Allow Sentry errors for Staging and Production

ckanext/datagovuk/ckan_patches/__init__.py, ckanext/datagovuk/ckan_patches/query.py, ckanext/datagovuk/tests/test_ckan_patches.py
Block calls to package search if they match all block tags and log a warning when it does this.
=> Block package search calls if matching block_tags

ckanext/datagovuk/plugin.py, ckanext/datagovuk/tests/test_user.py, ckanext/datagovuk/views/user.py
Add user route back in and update the user tests.
=> Add user route, fix user tests and remove redundant tests

Jenkinsfile, bin/install-dependencies.sh
Update the Jenkinsfile to detect changes on main branch for deployment
=> Update Jenkinsfile to deploy on main branch

ckanext/datagovuk/lib/organogram_xls_splitter.py
Fixed undefined object `xls_filename` should be `xls_stream`
=> Change xls_filename to xls_stream

bin/install-dependencies.sh
There isn't much information in the harvest logs currently to figure out what is causing the redis errors so add additional logging to help investigate the errors further.
https://trello.com/c/tlYrmfIV/2695-investigate-cause-of-redis-errors-appearing-in-dgu-sentry
=> Update harvest sha for extra redis error logging

bin/install-dependencies.sh
Add extra debug logs to attempt to identify the user attempting to access a package which is causing user auth errors.
Linked to this commit - 
https://github.com/alphagov/ckan/commit/aa83bb94b869ef9b15d5bb4a7789e5fa7d9130d2
https://trello.com/c/De5AG7yb/2703-investigate-cause-of-user-permissions-errors-on-datasets-reads
=> Update CKAN sha to add additional debug logs

bin/install-dependencies.sh, bin/jenkins-tests.sh
Update jenkins tests to use postgres 13.
https://trello.com/c/0LN3n9Aa/2-ckan
=> Update Jenkins tests to use Postgres 13

ckanext/datagovuk/templates/page.html
Show banner to users with dates for downtime due to database upgrade.
https://trello.com/c/lipeZ92R/50-prepare-comms-for-ckan-downtime
=> Add banner database upgrade

ckanext/datagovuk/lib/organogram_xls_splitter.py, public/publisher-files/Blank_Organogram_Template_latest.xls, tests/action/test_create.py
Update the blank organogram template to add Office Region.
https://trello.com/c/VKwyN1MA/724-work-on-dgu-organogram-things-coming-from-cabinet-office-transparency-team
=> Add office region organogram

docs/migration_runsheet.md
Code examples should be surrounded by triple-backticks.
Also helpful to be more specific in signposting the DB admin password.
Loosely related Trello: https://trello.com/c/0LHZ1zo7/2840-document-the-dbadmin-infrastructure
=> Formatting improvements

Jenkinsfile, Procfile, bin/install-dependencies.sh, requirements.txt
Reverts alphagov/ckanext-datagovuk#1190
=> Revert "Upgrade CKAN to 2.9.7"

.github/workflows/ci.yml, Procfile
The python 3.7 upgrade appears to have issues with ssl connections, so downgrade for now.
=> Use python 3.6 to run CKAN

.github/workflows/ci.yml
Reinstate the github action tests to run so that other orgs can submit changes to things like the organograms and see automated test results.
=> Update ci.yaml to use standard CKAN solr image

.gitignore, Dockerfile, bin/setup_ckan.sh, ckanext/datagovuk/lib/cli.py, ckanext/datagovuk/upload.py, docker/bootstrap.sh, docker/docker-compose-2.9.7-full.yml, docker/docker-compose-2.9.7.yml, docker/nginx/2.9.3/Dockerfile, docker/nginx/2.9.3/ckan.conf, docker/nginx/2.9.7/Dockerfile, docker/nginx/2.9.7/ckan.conf, docker/nginx/setup/ckan-2.9.3.conf, docker/nginx/setup/ckan-2.9.7.conf, docker/postgresql/Dockerfile.13, docker/postgresql/docker-entrypoint-initdb.d/01_create_datastore.sql, docker/postgresql/docker-entrypoint-initdb.d/02_setup_test_databases.sql, docker/postgresql/docker-entrypoint-initdb.d/postgis_03_create_pycsw.sql, docker/solr/Dockerfile, docker/solr/Dockerfile.solr8, docker/solr/schema.solr8.xml, docker/solr/schema.xml, docker/solr/solrconfig.xml, docker/start-ckan.sh, production.ini, tests/test_upload.py
Add docker files to enable running of the CKAN stack and the additional Publish and Find apps. 
Additional helper scripts are added to make it easier to start up a docker stack.
https://trello.com/c/7g9rKJp3/1074-create-ckan-docker-image-for-use-with-ckan-k8s-cluster
=> Add docker files to allow devs to run a full DGU stack

Dockerfile, bin/setup_pycsw.sh, ckanext/datagovuk/lib/cli.py, ckanext/datagovuk/upload.py, docker/docker-compose-2.9.7.yml, docker/nginx/2.9.7/ckan.conf, docker/pycsw/pycsw.cfg, production.ini, pycsw.Dockerfile
A number of changes have been made to accommodate deployment to a k8s cluster - 
- Update the upload code to check for access key and secrets and if they are set.
- Add pycsw dockerfile and update the docker-compose file to use it
- Create a default user to enable visual regression tests to pass
- update the spatial sha to one updated to work with pycsw
- use an updated production.ini to make it work better within a docker stack
https://trello.com/c/CxQutDOt/1115-update-ckan-helm-chart-to-run-on-integration-cluster
https://trello.com/c/uWgUDRoc/1103-fix-ckan-visual-regression-tests-to-run-against-297
=> Fix docker

.dockerignore
Specifically postgis docker build needs the iinitdb.d folder
=> docker files are needed so don't ignore docker

docker/ckan/2.9.3.Dockerfile, docker/docker-compose-2.9.3.yml
This will make it easier to develop the stack in line with the production version of CKAN.
=> Add 2.9.3 Dockerfile for CKAN

.github/workflows/create-pr-on-tags.yaml, .github/workflows/create-pr.yaml, docker/create-pr.sh
Create a PR on govuk-ckan-charts when a version tag is created. 
This will allow developers to test PRs out on integration before deploying to Staging and Production.
=> Create PRs on tag creation for Staging and Prod

.github/workflows/build-image-on-tags.yaml, .github/workflows/build-image.yaml, .github/workflows/create-pr-on-tags.yaml, docker/build-image.sh, docker/create-pr.sh
- Fix the create PR so that the branch name is used for checking out github and creating the PR
- also rename ghcr to build-image to make it clearer 
- and add in a build image for the tag version so that images can be quickly identified to a tagged release
=> Fix create pr add build image tags

.github/workflows/build-image-on-tags.yaml, .github/workflows/build-image.yaml, .github/workflows/ci.yml, docker/build-image.sh, docker/pycsw/2.4.0.Dockerfile, docker/pycsw/2.4.0f.Dockerfile, docker/solr/8-2.9f.Dockerfile
Update the spatial sha to fix pycsw load issues and the Solr schema so that it is not rejected by the pycsw server.
=> Add pycsw 2.4.0

.github/workflows/build-image.yaml, docker/pycsw/2.4.0g.Dockerfile
This will use the latest spatial sha to fix update_records for csw records
=> Update the spatial sha to fix csw update_records

.github/workflows/build-image-on-tags.yaml, .github/workflows/build-image.yaml
Update the versions on build-image-on-tags.yaml and set a note to remind the dev to keep them in sync with build-image.yaml
=> Update build image tag pycsw

.github/workflows/build-image-on-tags.yaml, .github/workflows/build-image.yaml, docker/ckan/2.9.9-base.Dockerfile, docker/pycsw/2.4.0i.Dockerfile
Spatial shas updated due to rename of ckanext-spatial to ckanext-spatial-datagovuk
=> Update spatial shas

docker/ckan/2.9.9-base.Dockerfile, docker/pycsw/2.4.0i.Dockerfile
It was initially renamed due to trying to remove access to sensitive data, that data has now been purged so its safe to revert back to original name
=> Update the spatial repo name for better clarity

docker/ckan/2.9.9-base.Dockerfile
https://trello.com/c/dlaUdBYJ/1233-fix-pycsw-content
=> Update spatial sha to fix csw xml encoding

.github/workflows/build-image-on-tags.yaml, .github/workflows/build-image.yaml, docker/pycsw/2.4.0j.Dockerfile
https://trello.com/c/dlaUdBYJ/1233-fix-pycsw-content
=> Update spatial sha for pycsw

docker/ckan/2.9.9.Dockerfile
Add missing quotes from pip install
=> Fix pip install lxml

.github/workflows/ci.yml
https://trello.com/c/tRSORszm/3489-add-security-scans-to-dgu-repos-2
=> Add security scans

ckanext/datagovuk/lib/cli.py
Organisation information is limited from the CKAN API as it only returns the slug. 
The organisation index will allow the Find app to easily access organisation information.
=> Add reindex_organisations to create an index of publishers in Solr

.github/workflows/build-image.yaml
Add in missing patch to the BUILD_TAGS
=> Update BUILD_TAGS for build_push_base

build-config.yaml, docker/ckan/2.10.4-base.Dockerfile, docker/ckan/2.10.4.Dockerfile, docker/pycsw/2.6.1.Dockerfile
This will stop the intermittent harvest failures experienced by some publishers.
=> Add user agent schema resolver spatial sha

.github/workflows/create-pr.yaml, build-config.yaml, docker/ckan/2.10.4-base.Dockerfile, docker/ckan/2.10.4.Dockerfile, docker/pycsw/2.6.1.Dockerfile
Also update the create-pr workflow to only get triggered on the main branch
=> Update spatial sha to use cryptography 42 in spatial extension

ckanext/datagovuk/templates/package/snippets/resource_form.html
This adds information about organogram validation errors.
I also corrected the link to the relevant guidance.
=> Update organogram publishing guidance

.github/workflows/ci.yml, .github/workflows/create-pr-on-tags.yaml, .github/workflows/create-pr.yaml
Description:
- Update `checkout` action to latest version
=> Update GitHub actions latest dependencies

.github/workflows/ci.yml
This commit stops CI from runnning if only markdown files have changed
=> ✨ Don't trigger CI when making doc changes

.github/actionlint.yml, .github/workflows/actionlint.yml, .github/workflows/build-image.yaml, .github/workflows/ci.yml, .github/workflows/create-pr-on-tags.yaml
Bulk Update: Addresses govuk-infrastructure#1361
=> Add Actionlint Checks
